-- UNION
SELECT STUDENT_NAME FROM StudentDB.students UNION SELECT EMPLOYEE_NAME FROM EmployeeDB.Employees;
SELECT CITY FROM ECommerceDB.Customers UNION SELECT CITY FROM EmployeeDB.Employees;
SELECT EMAIL FROM StudentDB.students UNION SELECT EMAIL FROM EmployeeDB.Employees;
SELECT PHONE_NUMBER FROM StudentDB.students UNION SELECT PHONE_NUMBER FROM ECommerceDB.Customers;
SELECT DEPARTMENT_NAME FROM StudentDB.students UNION SELECT DEPARTMENT_NAME FROM EmployeeDB.Employees;
SELECT NAME FROM StudentDB.students UNION SELECT NAME FROM ECommerceDB.Customers;
SELECT CATEGORY FROM ShoppingDB.Products1 UNION SELECT CATEGORY FROM ShoppingDB.Products2;
SELECT COURSE_NAME FROM COLLEGEDB.CURRENTCOURSES UNION SELECT COURSE_NAME FROM COLLEGEDB.COMPLETEDCOURSES;
SELECT CITY FROM ECommerceDB.Customers UNION SELECT CITY FROM ECommerceDB.SUPPLIERS;
SELECT EMPLOYEE_NAME FROM EmployeeDB.Employees UNION SELECT MANAGER_NAME FROM EmployeeDB.MANAGERS;
SELECT STUDENT_ID FROM StudentDB.students UNION SELECT STUDENT_ID FROM StudentDB.ALUMNI;
SELECT PRODUCT_ID FROM ShoppingDB.PRODUCTS UNION SELECT PRODUCT_ID FROM ShoppingDB.DISCONTINUEDPRODUCTS;
SELECT EMAIL_ID FROM ECommerceDB.Customers UNION SELECT EMAIL_ID FROM ECommerceDB.SUPPLIERS;
SELECT CITY FROM ECommerceDB.Customers UNION SELECT CITY FROM ECommerceDB.SUPPLIERS;
SELECT DEPARTMENT_ID FROM EmployeeDB.Employees UNION SELECT DEPARTMENT_ID FROM EmployeeDB.MANAGERS;
SELECT COURSE_ID FROM COLLEGEDB.CURRENTSTUDENTS UNION SELECT COURSE_ID FROM COLLEGEDB.PREVIOUSSTUDENTS;
SELECT NAME FROM StudentDB.STUDENTS UNION SELECT NAME FROM StudentDB.TEACHERS;
SELECT PHONE_NUMBER FROM EmployeeDB.Employees UNION SELECT PHONE_NUMBER FROM ECommerceDB.Customers;
SELECT LOCATION FROM TABLE1 UNION SELECT LOCATION FROM TABLE2;
SELECT ID FROM EmployeeDB.Employees1 UNION SELECT ID FROM EmployeeDB.Employees2;

-- UNION ALL 

SELECT STUDENT_NAME FROM StudentDB.STUDENTS UNION ALL SELECT EMPLOYEE_NAME FROM EmployeeDB.Employees;
SELECT CITY FROM ECommerceDB.Customers UNION ALL SELECT CITY FROM EmployeeDB.Employees;
SELECT EMAIL FROM StudentDB.STUDENTS UNION ALL SELECT EMAIL FROM ECommerceDB.Customers;
SELECT PHONE_NUMBER FROM EmployeeDB.Employees UNION ALL SELECT PHONE_NUMBER FROM CUSTOMERS;
SELECT DEPARTMENT_NAME FROM EmployeeDB.Employees UNION ALL SELECT DEPARTMENT_NAME FROM StudentDB.STUDENTS;
SELECT CATEGORY FROM ShoppingDB.PRODUCTS1 UNION ALL SELECT CATEGORY FROM ShoppingDB.PRODUCTS2;
SELECT COURSE_NAME FROM CollegeDB.CURRENTCOURSES UNION ALL SELECT COURSE_NAME FROM CollegeDB.COMPLETEDCOURSES;
SELECT CUSTOMER_NAME FROM ECommerceDB.Customers1 UNION ALL SELECT CUSTOMER_NAME FROM ECommerceDB.Customers2;
SELECT EMPLOYEE_ID FROM EmployeeDB.Employees1 UNION ALL SELECT EMPLOYEE_ID FROM EmployeeDB.Employees2;
SELECT PRODUCT_ID FROM ShoppingDB.PRODUCTS UNION ALL SELECT PRODUCT_ID FROM ShoppingDB.OLDPRODUCTS;
SELECT CITY FROM ECommerceDB.Customers UNION ALL SELECT CITY FROM ECommerceDB.SUPPLIERS;
SELECT COURSE_ID FROM CollegeDB.ENROLLMENTS1 UNION ALL SELECT COURSE_ID FROM CollegeDB.ENROLLMENTS2;
SELECT EMAIL_ID FROM EmployeeDB.Employees1 UNION ALL SELECT EMAIL_ID FROM EmployeeDB.Employees2;
SELECT STUDENT_ID FROM StudentDB.STUDENTS UNION ALL SELECT STUDENT_ID FROM StudentDB.ALUMNI;
SELECT DEPARTMENT_ID FROM EmployeeDB.Employees1 UNION ALL SELECT DEPARTMENT_ID FROM EmployeeDB.Employees2;
SELECT PRODUCT_NAME FROM ShoppingDB.PRODUCTS1 UNION ALL SELECT PRODUCT_NAME FROM ShoppingDB.PRODUCTS2;
SELECT PHONE_NUMBER FROM ECommerceDB.Customers1 UNION ALL SELECT PHONE_NUMBER FROM ECommerceDB.Customers2;
SELECT EMPLOYEE_NAME FROM EmployeeDB.Employees1 UNION ALL SELECT EMPLOYEE_NAME FROM EmployeeDB.Employees2;
SELECT LOCATION FROM ECommerceDB.Customers UNION ALL SELECT LOCATION FROM ECommerceDB.SUPPLIERS;
SELECT ID FROM TABLE1 UNION ALL SELECT ID FROM TABLE2; -- SYNTAX

-- INTERSECT 

SELECT CITY FROM ECommerceDB.Customers INTERSECT SELECT CITY FROM ECommerceDB.SUPPLIERS;
SELECT EMAIL FROM StudentDB.STUDENTS INTERSECT SELECT EMAIL FROM EmployeeDB.Employees;
SELECT PHONE_NUMBER FROM ECommerceDB.Customers INTERSECT SELECT PHONE_NUMBER FROM EmployeeDB.Employees;
SELECT DEPARTMENT_NAME FROM StudentDB.STUDENTS INTERSECT SELECT DEPARTMENT_NAME FROM EmployeeDB.Employees;
SELECT STUDENT_ID FROM StudentDB.STUDENTS INTERSECT SELECT STUDENT_ID FROM StudentDB.ALUMNI;
SELECT PRODUCT_ID FROM ShoppingDB.Products INTERSECT SELECT PRODUCT_ID FROM ShoppingDB.OLDPRODUCTS;
SELECT COURSE_ID FROM StudentDB.CURRENTSTUDENTS INTERSECT SELECT COURSE_ID FROM StudentDB.PREVIOUSSTUDENTS;
SELECT CITY FROM ECommerceDB.Customers INTERSECT SELECT CITY FROM ECommerceDB.SUPPLIERS;
SELECT EMPLOYEE_NAME FROM EmployeeDB.Employees INTERSECT SELECT MANAGER_NAME FROM EmployeeDB.MANAGERS;
SELECT CATEGORY FROM ShoppingDB.PRODUCTS1 INTERSECT SELECT CATEGORY FROM ShoppingDB.PRODUCTS2;
SELECT EMAIL_ID FROM ECommerceDB.Customers INTERSECT SELECT EMAIL_ID FROM ECommerceDB.SUPPLIERS;
SELECT PHONE_NUMBER FROM StudentDB.STUDENTS INTERSECT SELECT PHONE_NUMBER FROM ECommerceDB.Customers;
SELECT DEPARTMENT_ID FROM EmployeeDB.Employees INTERSECT SELECT DEPARTMENT_ID FROM EmployeeDB.MANAGERS;
SELECT COURSE_NAME FROM CollegeDB.Courses1 INTERSECT SELECT COURSE_NAME FROM CollegeDB.Courses2;
SELECT CUSTOMER_ID FROM ECommerceDB.CURRENTCUSTOMERS INTERSECT SELECT CUSTOMER_ID FROM ECommerceDB.PREVIOUSCUSTOMERS;
SELECT PRODUCT_NAME FROM ShoppingDB.Products INTERSECT SELECT PRODUCT_NAME FROM ShoppingDB.DISCONTINUEDPRODUCTS;
SELECT LOCATION FROM TABLE1 INTERSECT SELECT LOCATION FROM TABLE2;
SELECT EMPLOYEE_ID FROM EmployeeDB.Employees1 INTERSECT SELECT EMPLOYEE_ID FROM EmployeeDB.Employees2;
SELECT STUDENT_NAME FROM StudentDB.STUDENTS INTERSECT SELECT STUDENT_NAME FROM StudentDB.ALUMNI;
SELECT COLUMN_NAME FROM TABLE1 INTERSECT SELECT COLUMN_NAME FROM TABLE2; -- SYNTAX

-- EXCEPT 
SELECT CITY FROM ECommerceDB.Customers EXCEPT SELECT CITY FROM ECommerceDB.SUPPLIERS;
SELECT EMAIL FROM StudentDB.STUDENTS EXCEPT SELECT EMAIL FROM EmployeeDB.Employees;
SELECT PHONE_NUMBER FROM ECommerceDB.Customers EXCEPT SELECT PHONE_NUMBER FROM EmployeeDB.EMPLOYEES;
SELECT DEPARTMENT_NAME FROM StudentDB.STUDENTS EXCEPT SELECT DEPARTMENT_NAME FROM EmployeeDB.Employees;
SELECT STUDENT_ID FROM StudentDB.STUDENTS EXCEPT SELECT STUDENT_ID FROM StudentDB.ALUMNI;
SELECT PRODUCT_ID FROM ShoppingDB.Products EXCEPT SELECT PRODUCT_ID FROM ShoppingDB.OLDPRODUCTS;
SELECT COURSE_ID FROM StudentDB.CURRENTSTUDENTS EXCEPT SELECT COURSE_ID FROM StudentDB.PREVIOUSSTUDENTS;
SELECT CITY FROM ECommerceDB.Customers EXCEPT SELECT CITY FROM ECommerceDB.SUPPLIERS;
SELECT EMPLOYEE_NAME FROM EmployeeDB.Employees EXCEPT SELECT MANAGER_NAME FROM EmployeeDB.MANAGERS;
SELECT CATEGORY FROM ShoppingDB.Products1 EXCEPT SELECT CATEGORY FROM ShoppingDB.Products2;
SELECT EMAIL_ID FROM ECommerceDB.Customers EXCEPT SELECT EMAIL_ID FROM ECommerceDB.SUPPLIERS;
SELECT PHONE_NUMBER FROM StudentDB.STUDENTS EXCEPT SELECT PHONE_NUMBER FROM ECommerceDB.Customers;
SELECT DEPARTMENT_ID FROM EmployeeDB.Employees EXCEPT SELECT DEPARTMENT_ID FROM EmployeeDB.MANAGERS;
SELECT COURSE_NAME FROM CollegeDB.CURRENTCOURSES EXCEPT SELECT COURSE_NAME FROM CollegeDB.COMPLETEDCOURSES;
SELECT CUSTOMER_ID FROM ECommerceDB.CURRENTCUSTOMERS EXCEPT SELECT CUSTOMER_ID FROM ECommerceDB.PREVIOUSCUSTOMERS;
SELECT PRODUCT_NAME FROM ShoppingDB.Products EXCEPT SELECT PRODUCT_NAME FROM ShoppingDB.DISCONTINUEDPRODUCTS;
SELECT LOCATION FROM TABLE1 EXCEPT SELECT LOCATION FROM TABLE2;
SELECT EMPLOYEE_ID FROM EmployeeDB.Employees1 EXCEPT SELECT EMPLOYEE_ID FROM EmployeeDB.Employees2;
SELECT STUDENT_NAME FROM StudentDB.STUDENTS EXCEPT SELECT STUDENT_NAME FROM StudentDB.ALUMNI;
SELECT COLUMN_NAME FROM TABLE1 EXCEPT SELECT COLUMN_NAME FROM TABLE2; -- SYNTAX

-- IN 

SELECT * FROM EmployeeDB.Employees WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EmployeeDB.DEPARTMENTS);
SELECT * FROM StudentDB.students WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EmployeeDB.DEPARTMENTS);
SELECT * FROM ECommerceDB.Customers WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ECommerceDB.ORDERS);
SELECT * FROM ShoppingDB.Products WHERE PRODUCT_ID IN (SELECT PRODUCT_ID FROM ECommerceDB.ORDERS);
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EmployeeDB.EMPLOYEEPROJECTS);
SELECT * FROM StudentDB.students WHERE STUDENT_ID IN (SELECT STUDENT_ID FROM StudentDB.ENROLLMENTS);
SELECT * FROM ECommerceDB.CUSTOMERS WHERE CUSTOMER_ID IN (SELECT CUSTOMER_ID FROM ECommerceDB.ORDERS);
SELECT * FROM ShoppingDB.Products WHERE PRODUCT_ID IN (SELECT PRODUCT_ID FROM ShoppingDB.ORDERS);
SELECT * FROM EmployeeDB.Employees WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM EmployeeDB.DEPARTMENTS WHERE CITY = 'CHENNAI');
SELECT * FROM StudentDB.students WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM StudentDB.students WHERE DEPARTMENT_NAME IN ('DATA SCIENCE', 'IT'));

-- NOT IN 

SELECT * FROM ECommerceDB.CUSTOMERS WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM ECommerceDB.ORDERS);
SELECT * FROM ShoppingDB.Products WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM ShoppingDB.ORDERS);
SELECT * FROM StudentDB.students WHERE STUDENT_ID NOT IN (SELECT STUDENT_ID FROM StudentDB.ENROLLMENTS);
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM EmployeeDB.EMPLOYEEPROJECTS);
SELECT * FROM EmployeeDB.DEPARTMENTS WHERE DEPARTMENT_ID NOT IN (SELECT DEPARTMENT_ID FROM EmployeeDB.Employees);
SELECT * FROM ECommerceDB.CUSTOMERS WHERE CUSTOMER_ID NOT IN (SELECT CUSTOMER_ID FROM ECommerceDB.ORDERS);
SELECT * FROM ShoppingDB.Products WHERE PRODUCT_ID NOT IN (SELECT PRODUCT_ID FROM ShoppingDB.ORDERS);
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEE_ID NOT IN (SELECT EMPLOYEE_ID FROM EmployeeDB.EMPLOYEEPROJECTS);
SELECT * FROM StudentDB.students WHERE STUDENT_ID NOT IN (SELECT STUDENT_ID FROM StudentDB.ENROLLMENTS);
SELECT * FROM CollegeDB.Courses WHERE COURSE_ID NOT IN (SELECT COURSE_ID FROM CollegeDB.ENROLLMENTS);