-- A. INNER JOIN  

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.students S 
INNER JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTID, S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.students S
INNER JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM StudentDB.students S
INNER JOIN CollegeDB.Courses C
ON S.COURSEID = C.COURSEID;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME, C.COURSENAME
FROM StudentDB.students S
INNER JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID
INNER JOIN CollegeDB.Courses C
ON S.COURSEID = C.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.Employees E
INNER JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.Employees E
INNER JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.Customers C
INNER JOIN ShoppingDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT C.CUSTOMERNAME, O.QUANTITY
FROM ECommerceDB.Customers C
INNER JOIN ShoppingDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, P.PRODUCTNAME
FROM ShoppingDB.ORDERS O
INNER JOIN ShoppingDB.Products P
ON O.PRODUCTID = P.PRODUCTID;

SELECT O.ORDERID, P.PRODUCTNAME, O.QUANTITY
FROM ShoppingDB.ORDERS O
INNER JOIN ShoppingDB.Products P
ON O.PRODUCTID = P.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM ECommerceDB.Customers C
INNER JOIN ShoppingDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN ShoppingDB.PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME, O.QUANTITY
FROM ECommerceDB.Customers C
INNER JOIN ShoppingDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN ShoppingDB.PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM ShoppingDB.PRODUCTS P
INNER JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME, E.SALARY
FROM EmployeeDB.Employees E
INNER JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME, C.FEES
FROM StudentDB.students S
INNER JOIN CollegeDB.Courses C
ON S.COURSEID = C.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
WHERE D.DEPARTMENTNAME = 'IT';

SELECT S.STUDENTNAME, C.COURSENAME, C.FEES
FROM StudentDB.students S
INNER JOIN CollegeDB.Courses C
ON S.COURSEID = C.COURSEID
WHERE C.FEES > 30000;

SELECT DISTINCT C.CUSTOMERNAME
FROM ECommerceDB.Customers C
INNER JOIN ShoppingDB. ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT DISTINCT P.PRODUCTNAME
FROM ShoppingDB.PRODUCTS P
INNER JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME, O.QUANTITY, P.PRICE
FROM ECommerceDB.Customers C
INNER JOIN ShoppingDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
INNER JOIN ShoppingDB.PRODUCTS P
ON O.PRODUCTID = P.PRODUCTID;

-- LEFT JOIN 

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.students S
LEFT JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, S.STUDENTNAME
FROM StudentDB.DEPARTMENTS D
LEFT JOIN StudentDB.STUDENTS S
ON D.DEPARTMENTID = S.DEPARTMENTID;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.STUDENTS S
LEFT JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM StudentDB.STUDENTS S
LEFT JOIN CollegeDB.Courses C
ON S.COURSEID = C.COURSEID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM CollegeDB.Courses C
LEFT JOIN StudentDB.STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.Employees E
LEFT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
LEFT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM  ECommerceDB.Customers C
LEFT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.CUSTOMERS C
LEFT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, C.CUSTOMERNAME
FROM ECommerceDB.ORDERS O
LEFT JOIN ECommerceDB.CUSTOMERS C
ON O.CUSTOMERID = C.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM ShoppingDB.PRODUCTS P
LEFT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.PRODUCTS P
LEFT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, COUNT(O.ORDERID) AS TOTAL_ORDERS
FROM ECommerceDB.CUSTOMERS C
LEFT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
GROUP BY C.CUSTOMERNAME;

SELECT D.DEPARTMENTNAME, COUNT(E.EMPLOYEEID) AS EMPLOYEE_COUNT
FROM EmployeeDB.DEPARTMENTS D
LEFT JOIN EmployeeDB.Employees  E
ON D.DEPARTMENTID = E.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

SELECT C.COURSENAME, COUNT(S.STUDENTID) AS STUDENT_COUNT
FROM CollegeDB.Courses C
LEFT JOIN StudentDB.students S
ON C.COURSEID = S.COURSEID
GROUP BY C.COURSENAME;

SELECT P.PRODUCTNAME, SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM ShoppingDB.PRODUCTS P
LEFT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.PRODUCTNAME;

SELECT E.EMPLOYEENAME,
COALESCE(D.DEPARTMENTNAME, 'NOT ASSIGNED') AS DEPARTMENTNAME
FROM EmployeeDB.EMPLOYEES E
LEFT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECOMMERCEDB.CUSTOMERS C
LEFT JOIN ECOMMERCEDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.QUANTITY
FROM ShoppingDB.PRODUCTS P
LEFT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
LEFT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

-- RIGHT JOIN 

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.Employees E
RIGHT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.Employees E
RIGHT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM STUDENTDB.STUDENTS S
RIGHT JOIN STUDENTDB.COURSES C
ON S.COURSEID = C.COURSEID;

SELECT S.STUDENTNAME, C.COURSENAME
FROM STUDENTDB.STUDENTS S
RIGHT JOIN STUDENTDB.COURSES C
ON S.COURSEID = C.COURSEID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.Customers C
RIGHT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT O.ORDERID, C.CUSTOMERNAME
FROM ECommerceDB.CUSTOMERS C
RIGHT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID, O.QUANTITY
FROM ShoppingDB.Products P
RIGHT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT O.ORDERID, P.PRODUCTNAME
FROM ShoppingDB.PRODUCTS P
RIGHT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.Employees E
RIGHT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM STUDENTDB.STUDENTS S
RIGHT JOIN STUDENTDB.COURSES C
ON S.COURSEID = C.COURSEID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.Products P
RIGHT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.CUSTOMERS C
RIGHT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT D.DEPARTMENTNAME, COUNT(E.EMPLOYEEID) 
FROM EmployeeDB.EMPLOYEES E
RIGHT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID
GROUP BY D.DEPARTMENTNAME;

SELECT C.COURSENAME, COUNT(S.STUDENTID)
FROM STUDENTDB.STUDENTS S
RIGHT JOIN STUDENTDB.COURSES C
ON S.COURSEID = C.COURSEID
GROUP BY C.COURSENAME;

SELECT P.PRODUCTNAME, SUM(O.QUANTITY) AS TOTAL_QUANTITY
FROM ShoppingDB.PRODUCTS P
RIGHT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID
GROUP BY P.PRODUCTNAME;

-- FULL OUTER JOIN 

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.STUDENTS S
LEFT JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID
UNION
SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.STUDENTS S
RIGHT JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.EMPLOYEES E
LEFT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID

UNION

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.EMPLOYEES E
RIGHT JOIN EmployeeDB.DEPARTMENTS D
ON E.DEPARTMENTID = D.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.CUSTOMERS C
LEFT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID

UNION

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.CUSTOMERS C
RIGHT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.PRODUCTS P
LEFT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID

UNION

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.PRODUCTS P
RIGHT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT C.COURSENAME, S.STUDENTNAME
FROM CollegeDB.COURSES C
LEFT JOIN CollegeDB.STUDENTS S
ON C.COURSEID = S.COURSEID

UNION

SELECT C.COURSENAME, S.STUDENTNAME
FROM CollegeDB.COURSES C
RIGHT JOIN CollegeDB.STUDENTS S
ON C.COURSEID = S.COURSEID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
LEFT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID

UNION

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
RIGHT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM EmployeeDB.CUSTOMERS C
LEFT JOIN EmployeeDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID

UNION

SELECT C.CUSTOMERNAME, O.ORDERID
FROM EmployeeDB.CUSTOMERS C
RIGHT JOIN EmployeeDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID;

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.PRODUCTS P
LEFT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID

UNION

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.PRODUCTS P
RIGHT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
LEFT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID

UNION

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
RIGHT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID;

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
LEFT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE E.EMPLOYEEID IS NULL

UNION

SELECT D.DEPARTMENTNAME, E.EMPLOYEENAME
FROM EmployeeDB.DEPARTMENTS D
RIGHT JOIN EmployeeDB.EMPLOYEES E
ON D.DEPARTMENTID = E.DEPARTMENTID
WHERE D.DEPARTMENTID IS NULL;

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.CUSTOMERS C
LEFT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE O.ORDERID IS NULL

UNION

SELECT C.CUSTOMERNAME, O.ORDERID
FROM ECommerceDB.CUSTOMERS C
RIGHT JOIN ECommerceDB.ORDERS O
ON C.CUSTOMERID = O.CUSTOMERID
WHERE C.CUSTOMERID IS NULL;

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.PRODUCTS P
LEFT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID
WHERE O.ORDERID IS NULL

UNION

SELECT P.PRODUCTNAME, O.ORDERID
FROM ShoppingDB.PRODUCTS P
RIGHT JOIN ShoppingDB.ORDERS O
ON P.PRODUCTID = O.PRODUCTID
WHERE P.PRODUCTID IS NULL;

SELECT C.COURSENAME, S.STUDENTNAME
FROM CollegeDB.COURSES C
LEFT JOIN CollegeDB.STUDENTS S
ON C.COURSEID = S.COURSEID
WHERE S.STUDENTID IS NULL

UNION

SELECT C.COURSENAME, S.STUDENTNAME
FROM CollegeDB.COURSES C
RIGHT JOIN CollegeDB.STUDENTS S
ON C.COURSEID = S.COURSEID
WHERE C.COURSEID IS NULL;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.STUDENTS S
LEFT JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID

UNION

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM StudentDB.STUDENTS S
RIGHT JOIN StudentDB.DEPARTMENTS D
ON S.DEPARTMENTID = D.DEPARTMENTID;

-- CROSS JOIN 

SELECT S.STUDENTNAME, C.COURSENAME
FROM StudentDB.STUDENTS S
CROSS JOIN StudentDB.COURSES C;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.EMPLOYEES E
CROSS JOIN EmployeeDB.DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.CUSTOMERNAME
FROM EmployeeDB.PRODUCTS P
CROSS JOIN EmployeeDB.CUSTOMERS C;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM ECommerceDB.CUSTOMERS C
CROSS JOIN ECommerceDB.PRODUCTS P;

SELECT C.COURSENAME, D.DEPARTMENTNAME
FROM CollegeDB.COURSES C
CROSS JOIN CollegeDB.DEPARTMENTS D;

SELECT E.EMPLOYEENAME, C.COURSENAME
FROM EmployeeDB.EMPLOYEES E
CROSS JOIN CollegeDB.COURSES C;

SELECT S.STUDENTNAME, D.DEPARTMENTNAME
FROM STUDENTDB.STUDENTS S
CROSS JOIN STUDENTDB.DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.COURSENAME
FROM ShoppingDB.PRODUCTS P
CROSS JOIN CollegeDB.COURSES C;

SELECT C.CUSTOMERNAME, CO.COURSENAME
FROM ECommerceDB.CUSTOMERS C
CROSS JOIN CollegeDB.COURSES CO;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.EMPLOYEES E
CROSS JOIN EmployeeDB.DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.CUSTOMERNAME
FROM ShoppingDB.PRODUCTS P
CROSS JOIN ShoppingDB.CUSTOMERS C;

SELECT S.STUDENTNAME, C.COURSENAME
FROM ShoppingDB.STUDENTS S
CROSS JOIN CollegeDB.COURSES C;

SELECT E.EMPLOYEENAME, D.DEPARTMENTNAME
FROM EmployeeDB.EMPLOYEES E
CROSS JOIN EmployeeDB.DEPARTMENTS D;

SELECT P.PRODUCTNAME, C.COURSENAME
FROM ShoppingDB.PRODUCTS P
CROSS JOIN CollegeDB.COURSES C;

SELECT C.CUSTOMERNAME, P.PRODUCTNAME
FROM ECommerceDB.CUSTOMERS C
CROSS JOIN ShoppingDB.PRODUCTS P;

-- SELF JOIN 

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME
FROM EmployeeDB.EMPLOYEES E
LEFT JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.MANAGERID IS NULL;

SELECT E.EMPLOYEEID, E.EMPLOYEENAME, E.MANAGERID, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
LEFT JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
LEFT JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E.EMPLOYEENAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE M.DEPARTMENTID = (
    SELECT DEPARTMENTID
    FROM DEPARTMENTS
    WHERE DEPARTMENTNAME = 'IT'
);

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE M.SALARY > 70000;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.SALARY > M.SALARY;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.SALARY < M.SALARY;

SELECT E.EMPLOYEENAME, E.SALARY, M.EMPLOYEENAME AS MANAGERNAME, M.SALARY AS MANAGERSALARY
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;

SELECT E1.EMPLOYEENAME, E2.EMPLOYEENAME AS COLLEAGUE
FROM EmployeeDB.EMPLOYEES E1
INNER JOIN EmployeeDB.EMPLOYEES E2
ON E1.MANAGERID = E2.MANAGERID
AND E1.EMPLOYEEID <> E2.EMPLOYEEID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
LEFT JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
ORDER BY M.EMPLOYEENAME;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
INNER JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID
WHERE E.DEPARTMENTID = M.DEPARTMENTID;

SELECT E.EMPLOYEENAME, M.EMPLOYEENAME AS MANAGERNAME
FROM EmployeeDB.EMPLOYEES E
LEFT JOIN EmployeeDB.EMPLOYEES M
ON E.MANAGERID = M.EMPLOYEEID;