-- IS NULL

SELECT * FROM StudentDB.students WHERE EMAIL IS NULL;
SELECT * FROM StudentDB.students WHERE PHONE IS NULL;
SELECT * FROM EmployeeDB.Employees WHERE DEPARTMENT IS NULL;
SELECT * FROM EmployeeDB.Employees WHERE EMAIL IS NULL; 
SELECT * FROM HospitalDB.Patients WHERE DISEASE IS NULL;
SELECT * FROM HospitalDB.Patients WHERE DOCTORNAME IS NULL;
SELECT * FROM LibraryDB.Books WHERE PUBLISHEDYEAR IS NULL; 
SELECT * FROM LibraryDB.Books WHERE AUTHOR IS NULL;
SELECT * FROM ShoppingDB.Products WHERE BRAND IS NULL;
SELECT * FROM ShoppingDB.Products WHERE MANUFACTURINGDATE IS NULL;
SELECT * FROM ECommerceDB.Customers WHERE EMAIL IS NULL;
SELECT * FROM ECommerceDB.Customers WHERE COUNTRY IS NULL ;

-- IS NOT NULL

SELECT * FROM StudentDB.students WHERE EMAIL IS NOT NULL;
SELECT * FROM StudentDB.students WHERE DEPARTMENT IS NOT NULL;
SELECT * FROM EmployeeDB.Employees WHERE SALARY IS NOT NULL;
SELECT * FROM EmployeeDB.Employees WHERE EMAIL IS NOT NULL;
SELECT * FROM HospitalDB.Patients WHERE DISEASE IS NOT NULL;
SELECT * FROM HospitalDB.Patients WHERE DOCTORNAME IS NOT NULL;
SELECT * FROM LibraryDB.Books WHERE AUTHOR IS NOT NULL;
SELECT * FROM LibraryDB.Books WHERE PRICE IS NOT NULL;
SELECT * FROM ShoppingDB.Products WHERE BRAND IS NOT NULL;
SELECT * FROM ShoppingDB.Products WHERE MANUFACTURINGDATE IS NOT NULL;
SELECT * FROM ECommerceDB.Customers WHERE EMAIL IS NOT NULL;
SELECT * FROM ECommerceDB.Customers WHERE COUNTRY IS NOT NULL;

-- IS NULL WITH CONDITION

SELECT * FROM StudentDB.students WHERE EMAIL IS NULL AND DEPARTMENT = 'IT';
SELECT * FROM EmployeeDB.Employees WHERE DEPARTMENT IS NULL AND SALARY > 30000;
SELECT * FROM HospitalDB.Patients WHERE DISEASE IS NULL AND AGE > 25;
SELECT * FROM ShoppingDB.Products WHERE BRAND IS NULL AND PRICE > 5000;
SELECT * FROM ECommerceDB.Customers WHERE EMAIL IS NULL AND CITY = 'CHENNAI';

-- IS NOT NULL WITH CONDITION

SELECT * FROM StudentDB.students WHERE EMAIL IS NOT NULL AND DEPARTMENT = 'IT';
SELECT * FROM EmployeeDB.Employees WHERE DEPARTMENT IS NOT NULL AND SALARY > 30000;
SELECT * FROM HospitalDB.Patients WHERE DISEASE IS NOT NULL AND AGE > 25;
SELECT * FROM LibraryDB.Books WHERE PRICE IS NOT NULL;
SELECT * FROM ShoppingDB.Products WHERE BRAND IS NOT NULL AND PRICE > 5000;
SELECT * FROM ECommerceDB.Customers WHERE EMAIL IS NOT NULL AND CITY = 'CHENNAI';

-- MIXED PRACTICE
SELECT * FROM StudentDB.students WHERE EMAIL IS NULL OR DEPARTMENT = 'IT';
SELECT * FROM EmployeeDB.Employees WHERE EMAIL IS NOT NULL  AND (DEPARTMENT IN ('IT','HR'));
SELECT * FROM ShoppingDB.Products WHERE BRAND IS NULL OR DISCOUNT IS NULL;
SELECT * FROM ECommerceDB.Customers WHERE EMAIL IS NOT NULL AND COUNTRY IS NOT NULL;
SELECT * FROM HospitalDB.Patients WHERE DISEASE IS NULL AND PHONE IS NOT NULL;