-- ARITHMETIC EXPRESSIONS 

SELECT SALARY, SALARY + 5000 AS BONUS_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY, SALARY * 1.10 AS INCREMENTED_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY, SALARY - 2000 AS UPDATED_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY, SALARY * 12 AS ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY, SALARY * 0.95 AS MONTHLY_SALARY_AFTER_DEDUCTION FROM EmployeeDB.EMPLOYEES;
SELECT PRICE, PRICE * 1.18 AS PRICE_AFTER_GST FROM ShoppingDB.PRODUCTS;
SELECT PRICE, PRICE * 0.90 AS PRICE_AFTER_DISCOUNT FROM ShoppingDB.PRODUCTS;
SELECT PRICE, PRICE * 0.15 AS DISCOUNT_AMOUNT FROM ShoppingDB.PRODUCTS;
SELECT PRICE, PRICE * 1.10 AS PRICE_AFTER_TAX FROM LibraryDB.BOOKS;
SELECT PRICE, PRICE * 0.80 AS PRICE_AFTER_DISCOUNT FROM LibraryDB.BOOKS;
SELECT FEES, FEES * 1.05 AS FEES_AFTER_GST FROM CollegeDB.COURSES;
SELECT FEES, FEES * 0.90 AS FEES_AFTER_DISCOUNT FROM CollegeDB.COURSES;
SELECT PRICE, QUANTITY, PRICE * QUANTITY AS TOTAL_PRODUCT_VALUE FROM ShoppingDB.PRODUCTS;
SELECT PRICE, QUANTITY, PRICE * QUANTITY AS TOTAL_INVENTORY_VALUE FROM LibraryDB.BOOKS;
SELECT SALARY, (SALARY * 12) * 1.10 AS ANNUAL_SALARY_AFTER_INCREMENT FROM EmployeeDB.EMPLOYEES;
SELECT PRICE, (PRICE * 0.80) * 1.18 AS FINAL_PRICE FROM ShoppingDB.PRODUCTS;
SELECT SALARY, SALARY + 3000 AS TOTAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT FEES, FEES * 0.85 AS PAYABLE_FEES FROM CollegeDB.COURSES;
SELECT PRICE, STOCK_QUANTITY, PRICE * STOCK_QUANTITY AS TOTAL_STOCK_VALUE FROM ShoppingDB.PRODUCTS;
SELECT SALARY, SALARY - 50000 AS DIFFERENCE FROM EmployeeDB.EMPLOYEES;

-- COMPARISON EXPRESSIONS

SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY > 50000;
SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY < 30000;
SELECT * FROM StudentDB.STUDENTS WHERE AGE > 20;
SELECT * FROM StudentDB.STUDENTS WHERE AGE = 21;
SELECT * FROM ShoppingDB.PRODUCTS WHERE PRICE > 10000;
SELECT * FROM ShoppingDB.PRODUCTS WHERE STOCK_QUANTITY < 10;
SELECT * FROM LibraryDB.BOOKS WHERE PRICE BETWEEN 500 AND 1500;
SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY <> 40000;
SELECT * FROM StudentDB.STUDENTS WHERE AGE >= 18;
SELECT * FROM ShoppingDB.PRODUCTS WHERE PRICE <= 50000;
SELECT * FROM CollegeDB.COURSES WHERE FEES > 30000;
SELECT * FROM MovieDB.MOVIES WHERE RATING >= 4;
SELECT * FROM HospitalDB.PATIENTS WHERE AGE < 60;
SELECT * FROM ECommerceDB.CUSTOMERS WHERE AGE <> 25;
SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY BETWEEN 40000 AND 70000;

-- LOGICAL EXPRESSIONS

SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY > 40000 AND DEPARTMENT = 'IT';
SELECT * FROM StudentDB.STUDENTS WHERE AGE > 20 AND DEPARTMENT = 'CSE';
SELECT * FROM ShoppingDB.PRODUCTS WHERE PRICE > 10000 AND STOCK_QUANTITY > 10;
SELECT * FROM LibraryDB.BOOKS WHERE PRICE > 500 OR CATEGORY = 'TECHNOLOGY';
SELECT * FROM EmployeeDB.EMPLOYEES WHERE DEPARTMENT IN ('IT','HR');
SELECT * FROM StudentDB.STUDENTS WHERE DEPARTMENT <> 'IT';
SELECT * FROM ShoppingDB.PRODUCTS WHERE CATEGORY = 'ELECTRONICS' AND PRICE BETWEEN 10000 AND 50000;
SELECT * FROM ECommerceDB.CUSTOMERS WHERE CITY IN ('CHENNAI','BANGALORE');
SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY > 50000 AND DESIGNATION = 'DEVELOPER';
SELECT * FROM LibraryDB.BOOKS WHERE PRICE < 500 OR PRICE > 1500;
SELECT * FROM HospitalDB.PATIENTS WHERE AGE > 30 AND BLOOD_GROUP = 'O+';
SELECT * FROM StudentDB.STUDENTS WHERE DEPARTMENT = 'IT' OR AGE > 22;
SELECT * FROM ShoppingDB.PRODUCTS WHERE BRAND IS NOT NULL AND PRICE > 5000;
SELECT * FROM ECommerceDB.CUSTOMERS WHERE EMAIL IS NOT NULL AND CITY = 'CHENNAI';
SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY NOT BETWEEN 30000 AND 60000;

-- STRING EXPRESSIONS

SELECT UPPER(NAME) FROM StudentDB.STUDENTS;
SELECT LOWER(NAME) FROM EmployeeDB.EMPLOYEES;
SELECT NAME, LENGTH(NAME) AS NAME_LENGTH FROM StudentDB.STUDENTS;
SELECT NAME, LEFT(NAME,3) AS FIRST_3_CHARACTERS FROM EmployeeDB.EMPLOYEES;
SELECT NAME, RIGHT(NAME,2) AS LAST_2_CHARACTERS FROM StudentDB.STUDENTS;
SELECT UPPER(PRODUCT_NAME) AS PRODUCT_NAME, PRICE FROM ShoppingDB.PRODUCTS;
SELECT NAME, LENGTH(NAME) AS NAME_LENGTH FROM ECommerceDB.CUSTOMERS;
SELECT TRIM(BOOK_NAME) FROM LibraryDB.BOOKS;
SELECT CONCAT(FIRST_NAME,' ',DEPARTMENT) AS STUDENT_DETAILS FROM StudentDB.STUDENTS;
SELECT CONCAT(NAME,' - ',SALARY) AS EMPLOYEE_DETAILS FROM EmployeeDB.EMPLOYEES;
SELECT CONCAT(PRODUCT_NAME,' - ',BRAND) AS PRODUCT_DETAILS FROM ShoppingDB.PRODUCTS;
SELECT CONCAT(CITY,' - ',STATE) AS LOCATION FROM ECommerceDB.CUSTOMERS;
SELECT CONCAT(COURSE_NAME,' - ',DEPARTMENT) AS COURSE_DETAILS FROM CollegeDB.COURSES;
SELECT LEFT(NAME,1) AS FIRST_CHARACTER FROM StudentDB.STUDENTS;
SELECT RIGHT(NAME,1) AS LAST_CHARACTER FROM EmployeeDB.EMPLOYEES;

-- DATE & TIME EXPRESSIONS 

SELECT CURRENT_DATE();
SELECT CURRENT_TIME();
SELECT CURRENT_TIMESTAMP();
SELECT NOW();
SELECT JOINING_DATE, DATE_ADD(JOINING_DATE, INTERVAL 30 DAY) AS DATE_AFTER_30_DAYS FROM EmployeeDB.EMPLOYEES;
SELECT JOINING_DATE, DATE_SUB(JOINING_DATE, INTERVAL 90 DAY) AS DATE_BEFORE_90_DAYS FROM EmployeeDB.EMPLOYEES;
SELECT ADMISSION_DATE, DATE_ADD(ADMISSION_DATE, INTERVAL 7 DAY) AS DATE_AFTER_7_DAYS FROM PATIENTS;
SELECT REGISTRATION_DATE, DATE_SUB(REGISTRATION_DATE, INTERVAL 42 DAY) AS DATE_BEFORE_42_DAYS FROM ECommerceDB.CUSTOMERS;
SELECT MANUFACTURING_DATE, DATE_ADD(MANUFACTURING_DATE, INTERVAL 126 DAY) AS DATE_AFTER_126_DAYS FROM ShoppingDB.PRODUCTS;
SELECT DATE_FORMAT(JOINING_DATE,'%d-%m-%Y') AS FORMATTED_DATE FROM EmployeeDB.EMPLOYEES;
SELECT DATE_FORMAT(REGISTRATION_DATE,'%m/%d/%Y') AS FORMATTED_DATE FROM ECommerceDB.CUSTOMERS;
SELECT DATE_FORMAT(MANUFACTURING_DATE,'%d-%M-%Y') AS FORMATTED_DATE FROM ShoppingDB.PRODUCTS;
SELECT YEAR(JOINING_DATE) AS JOINING_YEAR FROM EmployeeDB.EMPLOYEES;
SELECT MONTH(REGISTRATION_DATE) AS REGISTRATION_MONTH FROM ECommerceDB.CUSTOMERS;
SELECT DAY(MANUFACTURING_DATE) AS MANUFACTURING_DAY FROM ShoppingDB.PRODUCTS;

-- AGGREGATE EXPRESSIONS

SELECT SUM(SALARY) AS TOTAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT MAX(SALARY) AS HIGHEST_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT MIN(SALARY) AS LOWEST_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EmployeeDB.EMPLOYEES;
SELECT SUM(PRICE * QUANTITY) AS TOTAL_PRODUCT_VALUE FROM ShoppingDB.PRODUCTS;
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM ShoppingDB.PRODUCTS;
SELECT MAX(PRICE) AS HIGHEST_BOOK_PRICE FROM LibraryDB.BOOKS;
SELECT MIN(FEES) AS LOWEST_COURSE_FEE FROM CollegeDB.COURSES;
SELECT COUNT(*) AS PRODUCT_COUNT FROM ShoppingDB.PRODUCTS WHERE PRICE > 10000;

-- EXPRESSION WITH ALIAS

SELECT SALARY AS MONTHLY_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY * 12 AS ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT PRICE * 0.90 AS DISCOUNTED_PRICE FROM ShoppingDB.PRODUCTS;
SELECT PRICE * 1.18 AS FINAL_PRICE FROM ShoppingDB.PRODUCTS;
SELECT PRICE * STOCK_QUANTITY AS STOCK_VALUE FROM ShoppingDB.PRODUCTS;
SELECT PRICE * 0.90 AS DISCOUNTED_PRICE FROM LibraryDB.BOOKS;
SELECT FEES * 0.85 AS FINAL_FEES FROM CollegeDB.COURSES;
SELECT LENGTH(NAME) AS NAME_LENGTH FROM StudentDB.STUDENTS;
SELECT SALARY * 1.10 AS INCREMENTED_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT PRICE * STOCK_QUANTITY AS TOTAL_VALUE FROM ShoppingDB.PRODUCTS;