-- GROUP BY 

SELECT DEPARTMENT, COUNT(*) FROM EmployeeDB.Employees GROUP BY DEPARTMENT;
SELECT DEPARTMENT, COUNT(*) FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT CATEGORY, COUNT(*) FROM ShoppingDB.Products GROUP BY CATEGORY;
SELECT CITY, COUNT(*) FROM EcommerceDB.CUSTOMERS GROUP BY CITY;
SELECT DESIGNATION, COUNT(*) FROM EmployeeDB.Employees GROUP BY DESIGNATION;
SELECT COURSE, COUNT(*) FROM StudentDB.students GROUP BY COURSE;
SELECT DEPARTMENT, SUM(SALARY) FROM EmployeeDB.Employees GROUP BY DEPARTMENT;
SELECT DEPARTMENT, AVG(SALARY) FROM EmployeeDB.Employees GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MIN(SALARY) FROM EmployeeDB.Employees GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MAX(SALARY) FROM EmployeeDB.Employees GROUP BY DEPARTMENT;
SELECT CATEGORY, SUM(STOCK) FROM ShoppingDB.Products GROUP BY CATEGORY;
SELECT CATEGORY, AVG(PRICE) FROM ShoppingDB.Products GROUP BY CATEGORY;
SELECT CATEGORY, MIN(PRICE) FROM ShoppingDB.Products GROUP BY CATEGORY;
SELECT CATEGORY, MAX(PRICE) FROM ShoppingDB.Products GROUP BY CATEGORY;
SELECT DEPARTMENT, SUM(FEES) FROM CollegeDB.Courses GROUP BY DEPARTMENT;
SELECT DEPARTMENT, AVG(FEES) FROM CollegeDB.Courses GROUP BY DEPARTMENT;
SELECT CITY, COUNT(*) FROM EcommerceDB.CUSTOMERS GROUP BY CITY;
SELECT PRODUCT_ID, SUM(QUANTITY) FROM ShoppingDB.ORDERS GROUP BY PRODUCT_ID;
SELECT CUSTOMER_ID, SUM(ORDER_AMOUNT) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID;
SELECT YEAR(JOINING_DATE), COUNT(*) FROM EmployeeDB.EMPLOYEES GROUP BY YEAR(JOINING_DATE);

-- GROUP BY WITH COUNT() 

SELECT DEPARTMENT, COUNT(*) FROM EmployeeDB.Employees GROUP BY DEPARTMENT;
SELECT DEPARTMENT, COUNT(*) FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT CATEGORY, COUNT(*) FROM ShoppingDB.Products GROUP BY CATEGORY;
SELECT CITY, COUNT(*) FROM EcommerceDB.CUSTOMERS GROUP BY CITY;
SELECT JOB_ROLE, COUNT(*) FROM EmployeeDB.Employees GROUP BY JOB_ROLE;
SELECT COURSE, COUNT(*) FROM StudentDB.students GROUP BY COURSE;
SELECT CUSTOMER_ID, COUNT(*) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID;
SELECT PRODUCT_ID, COUNT(*) FROM ShoppingDB.ORDERS GROUP BY PRODUCT_ID;
SELECT YEAR(HIRE_DATE), COUNT(*) FROM EmployeeDB.Employees GROUP BY YEAR(HIRE_DATE);
SELECT GENDER, COUNT(*) FROM StudentDB.students GROUP BY GENDER;
SELECT BRAND, COUNT(*) FROM ShoppingDB.Products GROUP BY BRAND;
SELECT STATE, COUNT(*) FROM EcommerceDB.CUSTOMERS GROUP BY STATE;
SELECT EXPERIENCE_LEVEL, COUNT(*) FROM EmployeeDB.Employees GROUP BY EXPERIENCE_LEVEL;
SELECT AUTHOR, COUNT(*) FROM LibraryDB.Books GROUP BY AUTHOR;
SELECT DEPARTMENT, COUNT(*) FROM CollegeDB.Courses GROUP BY DEPARTMENT;

-- GROUP BY WITH SUM()

SELECT DEPARTMENT, SUM(SALARY)FROM EmployeeDB.Employees GROUP BY DEPARTMENT;
SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) FROM EcommerceDB.SALES GROUP BY CUSTOMER_ID;
SELECT PRODUCT_ID, SUM(QUANTITY) FROM ShoppingDB.ORDERS GROUP BY PRODUCT_ID;
SELECT CATEGORY, SUM(STOCK) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY;
SELECT CATEGORY, SUM(PRICE * STOCK)FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY;
SELECT DEPARTMENT, SUM(FEES)FROM CollegeDB.COURSES GROUP BY DEPARTMENT;
SELECT JOB_ROLE, SUM(SALARY)FROM EmployeeDB.EMPLOYEES GROUP BY JOB_ROLE;
SELECT CITY, SUM(SALES_AMOUNT)FROM EcommerceDB.SALES GROUP BY CITY;
SELECT MONTH(ORDER_DATE), SUM(ORDER_AMOUNT) FROM ShoppingDB.ORDERS GROUP BY MONTH(ORDER_DATE);
SELECT CATEGORY, SUM(QUANTITY) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY;
SELECT BRAND, SUM(PRICE * STOCK) FROM ShoppingDB.PRODUCTS GROUP BY BRAND;
SELECT YEAR(HIRE_DATE), SUM(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY YEAR(HIRE_DATE);
SELECT CUSTOMER_ID, SUM(SALES_AMOUNT) FROM EcommerceDB.SALES GROUP BY CUSTOMER_ID;
SELECT COURSE, SUM(FEES) FROM CollegeDB.COURSES GROUP BY COURSE;
SELECT CUSTOMER_ID, SUM(QUANTITY) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID;

-- GROUP BY WITH AVG(), MIN(), MAX() 

SELECT DEPARTMENT, AVG(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MAX(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MIN(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT;
SELECT CATEGORY, AVG(PRICE) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY;
SELECT CATEGORY, MAX(PRICE) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY;
SELECT CATEGORY, MIN(PRICE) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY;
SELECT DEPARTMENT, AVG(MARKS) FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MAX(MARKS) FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MIN(MARKS) FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT DEPARTMENT, AVG(FEES) FROM CollegeDB.COURSES GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MAX(FEES) FROM CollegeDB.COURSES GROUP BY DEPARTMENT;
SELECT DEPARTMENT, MIN(FEES) FROM CollegeDB.COURSES GROUP BY DEPARTMENT;
SELECT CUSTOMER_ID, AVG(ORDER_AMOUNT) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID;
SELECT CUSTOMER_ID, MAX(ORDER_AMOUNT) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID;
SELECT CUSTOMER_ID, MIN(ORDER_AMOUNT) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID;

-- HAVING
SELECT DEPARTMENT, COUNT(*) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING COUNT(*) > 5;
SELECT DEPARTMENT, COUNT(*) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING COUNT(*) < 5;
SELECT DEPARTMENT, COUNT(*) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING COUNT(*) = 5;
SELECT DEPARTMENT, AVG(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING AVG(SALARY) > 50000;
SELECT DEPARTMENT, AVG(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING AVG(SALARY) < 40000;
SELECT DEPARTMENT, MAX(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING MAX(SALARY) > 100000;
SELECT DEPARTMENT, MIN(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING MIN(SALARY) > 30000;
SELECT CATEGORY, COUNT(*) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY HAVING COUNT(*) > 10;
SELECT CATEGORY, AVG(PRICE) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY HAVING AVG(PRICE) > 5000;
SELECT CATEGORY, SUM(STOCK) FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY HAVING SUM(STOCK) > 1000;
SELECT CITY, COUNT(*) FROM EcommerceDB.CUSTOMERS GROUP BY CITY HAVING COUNT(*) > 20;
SELECT CUSTOMER_ID, COUNT(*) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID HAVING COUNT(*) > 5;
SELECT PRODUCT_ID, COUNT(*) FROM ShoppingDB.ORDERS GROUP BY PRODUCT_ID HAVING COUNT(*) > 10;
SELECT DEPARTMENT, SUM(SALARY) FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT HAVING SUM(SALARY) > 500000;
SELECT COURSE, COUNT(*) FROM StudentDB.STUDENTS GROUP BY COURSE HAVING COUNT(*) > 30;

-- WHERE + GROUP BY + HAVING 

SELECT DEPARTMENT, COUNT(*) FROM  EmployeeDB.EMPLOYEES
WHERE SALARY > 30000 GROUP BY DEPARTMENT HAVING COUNT(*) > 5;

SELECT DEPARTMENT, AVG(SALARY) FROM  EmployeeDB.EMPLOYEES
WHERE EXPERIENCE > 2 GROUP BY DEPARTMENT HAVING AVG(SALARY) > 50000;

SELECT CUSTOMER_ID, SUM(ORDER_AMOUNT) FROM ShoppingDB.ORDERS
WHERE ORDER_AMOUNT > 1000 GROUP BY CUSTOMER_ID HAVING SUM(ORDER_AMOUNT) > 10000;

SELECT CATEGORY, COUNT(*) FROM ShoppingDB.PRODUCTS 
WHERE PRICE > 500 GROUP BY CATEGORY HAVING COUNT(*) > 5;

SELECT DEPARTMENT, AVG(MARKS) FROM StudentDB.STUDENTS
WHERE MARKS > 40 GROUP BY DEPARTMENT HAVING AVG(MARKS) > 70;

SELECT CATEGORY, SUM(STOCK) AS TOTAL_STOCK FROM ShoppingDB.PRODUCTS
WHERE STOCK > 10 GROUP BY CATEGORY HAVING SUM(STOCK) > 500;

SELECT CITY, COUNT(*) FROM EcommerceDB.CUSTOMERS
WHERE AGE > 18 GROUP BY CITY HAVING COUNT(*) > 10;

SELECT DEPARTMENT, AVG(FEES) FROM CollegeDB.Courses
WHERE FEES > 20000 GROUP BY DEPARTMENT HAVING AVG(FEES) > 30000;

SELECT CUSTOMER_ID, COUNT(*) FROM ShoppingDB.ORDERS
WHERE ORDER_AMOUNT > 5000 GROUP BY CUSTOMER_ID HAVING COUNT(*) > 3;

SELECT DEPARTMENT, SUM(SALARY) FROM EmployeeDB.Employees
WHERE SALARY > 40000 GROUP BY DEPARTMENT HAVING SUM(SALARY) > 300000;

-- GROUP BY MULTIPLE COLUMNS 

SELECT DEPARTMENT, DESIGNATION, COUNT(*) FROM EmployeeDB.Employees GROUP BY DEPARTMENT, DESIGNATION;
SELECT DEPARTMENT, DESIGNATION, AVG(SALARY) FROM EmployeeDB.Employees GROUP BY DEPARTMENT, DESIGNATION;
SELECT DEPARTMENT, GENDER, COUNT(*) FROM StudentDB.students GROUP BY DEPARTMENT, GENDER;
SELECT DEPARTMENT, GENDER, AVG(MARKS) FROM StudentDB.students GROUP BY DEPARTMENT, GENDER;
SELECT CATEGORY, BRAND, COUNT(*) FROM ShoppingDB.Products GROUP BY CATEGORY, BRAND;
SELECT CATEGORY, BRAND, AVG(PRICE) FROM ShoppingDB.Products GROUP BY CATEGORY, BRAND;
SELECT CUSTOMER_ID, CITY, SUM(SALES_AMOUNT) FROM EcommerceDB.SALES GROUP BY CUSTOMER_ID, CITY;
SELECT CUSTOMER_ID, PRODUCT_ID, SUM(QUANTITY) FROM ShoppingDB.ORDERS GROUP BY CUSTOMER_ID, PRODUCT_ID;
SELECT CITY, STATE, COUNT(*) FROM EcommerceDB.CUSTOMERS GROUP BY CITY, STATE;
SELECT DEPARTMENT, JOB_ROLE, SUM(SALARY) FROM EmployeeDB.Employees GROUP BY DEPARTMENT, JOB_ROLE HAVING SUM(SALARY) > 200000;