-- ORDER BY – SINGLE COLUMN

SELECT * FROM STUDENTDB.STUDENTS ORDER BY NAME ASC;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY NAME DESC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY SALARY ASC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY SALARY DESC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY PRICE ASC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY PRICE DESC;
SELECT * FROM LibraryDB.BOOKS ORDER BY BOOK_PRICE ASC;
SELECT * FROM LibraryDB.BOOKS ORDER BY BOOK_PRICE DESC;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY AGE ASC;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY AGE DESC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY JOINING_DATE ASC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY JOINING_DATE DESC;
SELECT * FROM CollegeDB.COURSES ORDER BY FEES ASC;
SELECT * FROM CollegeDB.COURSES ORDER BY FEES DESC;
SELECT * FROM MovieDB.MOVIES ORDER BY RATING DESC;
SELECT * FROM ECommerceDB.CUSTOMERS ORDER BY CITY ASC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY STOCK_QUANTITY DESC;
SELECT * FROM HospitalDB.PATIENTS ORDER BY AGE ASC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY EXPERIENCE DESC;
SELECT * FROM LibraryDB.BOOKS ORDER BY PUBLICATION_YEAR ASC;

-- ORDER BY WITH WHERE

SELECT * FROM EmployeeDB.EMPLOYEES WHERE DEPARTMENT = 'IT' ORDER BY SALARY ASC;
SELECT * FROM EmployeeDB.EMPLOYEES WHERE DEPARTMENT = 'IT' ORDER BY SALARY DESC;
SELECT * FROM STUDENTDB.STUDENTS WHERE DEPARTMENT = 'CSE' ORDER BY AGE DESC;
SELECT * FROM ShoppingDB.PRODUCTS WHERE CATEGORY = 'ELECTRONICS' ORDER BY PRICE ASC;
SELECT * FROM LibraryDB.BOOKS WHERE BOOK_PRICE > 500 ORDER BY BOOK_PRICE DESC;
SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY > 40000 ORDER BY SALARY ASC;
SELECT * FROM STUDENTDB.STUDENTS WHERE AGE > 20 ORDER BY NAME ASC;
SELECT * FROM ShoppingDB.PRODUCTS WHERE STOCK_QUANTITY < 10 ORDER BY STOCK_QUANTITY ASC;
SELECT * FROM CollegeDB.COURSES WHERE FEES > 30000 ORDER BY FEES DESC;
SELECT * FROM ECommerceDB.CUSTOMERS WHERE CITY = 'CHENNAI' ORDER BY CUSTOMER_NAME ASC;

-- ORDER BY WITH MULTIPLE COLUMNS

SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY DEPARTMENT ASC, SALARY DESC;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY DEPARTMENT ASC, AGE DESC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY CATEGORY ASC, PRICE DESC;
SELECT * FROM LibraryDB.BOOKS ORDER BY CATEGORY ASC, PRICE ASC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY DESIGNATION ASC, SALARY DESC;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY GENDER ASC, MARKS DESC;
SELECT * FROM ECommerceDB.CUSTOMERS ORDER BY CITY ASC, CUSTOMER_NAME ASC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY BRAND ASC, PRICE DESC;
SELECT * FROM CollegeDB.COURSES ORDER BY DEPARTMENT ASC, FEES DESC;
SELECT * FROM HospitalDB.PATIENTS ORDER BY BLOOD_GROUP ASC, AGE DESC;

-- ORDER BY WITH EXPRESSIONS

SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY SALARY * 12 DESC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY PRICE * QUANTITY DESC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY SALARY * 1.10 ASC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY PRICE * 0.90 ASC;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY LENGTH(NAME) DESC;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY SALARY * 12 ASC;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY PRICE * QUANTITY DESC;
SELECT * FROM LibraryDB.BOOKS ORDER BY PRICE * 0.80 ASC;
SELECT * FROM CollegeDB.COURSES ORDER BY FEES * 0.85 ASC;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY AGE + 1 ASC;

-- ORDER BY WITH ALIAS

SELECT NAME, SALARY * 12 AS ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES ORDER BY ANNUAL_SALARY DESC;
SELECT PRODUCT_NAME, PRICE * QUANTITY AS TOTAL_VALUE FROM ShoppingDB.PRODUCTS ORDER BY TOTAL_VALUE DESC;
SELECT NAME, LENGTH(NAME) AS NAME_LENGTH FROM STUDENTDB.STUDENTS ORDER BY NAME_LENGTH ASC;
SELECT NAME, SALARY * 1.10 AS INCREMENTED_SALARY FROM EmployeeDB.EMPLOYEES ORDER BY INCREMENTED_SALARY DESC;
SELECT PRODUCT_NAME, PRICE * 0.90 AS DISCOUNTED_PRICE FROM ShoppingDB.PRODUCTS ORDER BY DISCOUNTED_PRICE ASC;
SELECT COURSE_NAME, FEES * 0.85 AS FINAL_FEES FROM CollegeDB.COURSES ORDER BY FINAL_FEES DESC;
SELECT NAME, CASE WHEN AGE < 18 THEN 'MINOR' ELSE 'ADULT' END AS AGE_CATEGORY FROM STUDENTDB.STUDENTS ORDER BY AGE_CATEGORY;
SELECT NAME, CASE WHEN SALARY >= 50000 THEN 'HIGH' ELSE 'LOW' END AS SALARY_CATEGORY FROM EmployeeDB.EMPLOYEES ORDER BY SALARY_CATEGORY;
SELECT PRODUCT_NAME, CASE WHEN STOCK_QUANTITY > 0 THEN 'IN STOCK' ELSE 'OUT OF STOCK' END AS STOCK_STATUS FROM ShoppingDB.PRODUCTS ORDER BY STOCK_STATUS;
SELECT MOVIE_NAME, CASE WHEN RATING >= 4 THEN 'GOOD' ELSE 'AVERAGE' END AS RATING_CATEGORY FROM MovieDB.MOVIES ORDER BY RATING_CATEGORY;

-- ORDER BY WITH AGGREGATE FUNCTIONS

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT ORDER BY EMPLOYEE_COUNT DESC;
SELECT DEPARTMENT, COUNT(*) AS STUDENT_COUNT FROM STUDENTDB.STUDENTS GROUP BY DEPARTMENT ORDER BY STUDENT_COUNT ASC;
SELECT DEPARTMENT, AVG(SALARY) AS AVG_SALARY FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT ORDER BY AVG_SALARY DESC;
SELECT DEPARTMENT, MIN(SALARY) AS MIN_SALARY FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT ORDER BY MIN_SALARY ASC;
SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT ORDER BY MAX_SALARY DESC;
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT ORDER BY TOTAL_SALARY DESC;
SELECT CATEGORY, AVG(PRICE) AS AVG_PRICE FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY ORDER BY AVG_PRICE DESC;
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY ORDER BY MAX_PRICE DESC;
SELECT CATEGORY, MIN(PRICE) AS MIN_PRICE FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY ORDER BY MIN_PRICE ASC;
SELECT CATEGORY, SUM(STOCK_QUANTITY) AS TOTAL_STOCK FROM ShoppingDB.PRODUCTS GROUP BY CATEGORY ORDER BY TOTAL_STOCK DESC;

-- ADVANCED PRACTICE

SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY SALARY DESC LIMIT 5;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY PRICE ASC LIMIT 5;
SELECT * FROM LibraryDB.BOOKS ORDER BY PRICE DESC LIMIT 3;
SELECT * FROM STUDENTDB.STUDENTS ORDER BY MARKS DESC LIMIT 10;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY EXPERIENCE DESC LIMIT 5;
SELECT * FROM ShoppingDB.PRODUCTS ORDER BY PRICE * STOCK_QUANTITY DESC LIMIT 5;
SELECT * FROM CollegeDB.COURSES ORDER BY FEES DESC LIMIT 3;
SELECT * FROM MovieDB.MOVIES ORDER BY RATING DESC LIMIT 5;
SELECT * FROM EmployeeDB.EMPLOYEES ORDER BY JOINING_DATE DESC LIMIT 10;
SELECT * FROM ECommerceDB.CUSTOMERS ORDER BY REGISTRATION_DATE DESC LIMIT 5;