-- UPDATE - SINGLE COLUMN

UPDATE   StudentDB.students 
SET DEPARTMENT = 'COMPUTER SCIENCE' 
WHERE STUDENTID = 101;

SELECT * FROM StudentDB.students  
WHERE STUDENTID = 101;

UPDATE  EmployeeDB.Employees
SET SALARY = 55000
WHERE EMPLOYEEID = 201;

SELECT * FROM EmployeeDB.Employees
WHERE EMPLOYEEID = 201;

UPDATE HOSPITALDB.PATIENTS
SET DISEASE = 'FEVER'
WHERE PATIENTID = 301;

SELECT * FROM  HOSPITALDB.PATIENTS
WHERE PATIENTID = 301;

UPDATE LIBRARYDB.BOOKS
SET PRICE = 750
WHERE BOOKID = 401;

SELECT * FROM LIBRARYDB.BOOKS
WHERE BOOKID = 401;

UPDATE SHOPPINGDB.PRODUCTS
SET PRICE = 2500
WHERE PRODUCTID =  501;

SELECT * FROM SHOPPINGDB.PRODUCTS
WHERE PRODUCTID =  501;

-- UPDATE MULTIPLE COLUMNS

UPDATE   StudentDB.students 
SET AGE= 22,DEPARTMENT = 'COMPUTER SCIENCE' 
WHERE STUDENTID = 102;

SELECT * FROM StudentDB.students  
WHERE STUDENTID = 102;

UPDATE  EmployeeDB.Employees
SET SALARY = 55000,DEPARTMENT = 'SALES'
WHERE EMPLOYEEID = 202;

SELECT * FROM EmployeeDB.Employees
WHERE EMPLOYEEID = 202;

UPDATE HOSPITALDB.PATIENTS
SET DISEASE = 'FEVER', PHONE = 9874563210
WHERE PATIENTID = 302;

SELECT * FROM  HOSPITALDB.PATIENTS
WHERE PATIENTID = 302;

UPDATE LIBRARYDB.BOOKS
SET PRICE = 750,AUTHOR = 'SUJI'
WHERE BOOKID = 402;

SELECT * FROM LIBRARYDB.BOOKS
WHERE BOOKID = 402;

UPDATE SHOPPINGDB.PRODUCTS
SET PRICE = 2500, BRAND = 'CELLO'
WHERE PRODUCTID =  502;

SELECT * FROM SHOPPINGDB.PRODUCTS
WHERE PRODUCTID =  502;

-- UPDATE - USING CONDITION

UPDATE EmployeeDB.Employees
SET SALARY = SALARY * 0.10
WHERE DEPARTMENT = 'IT';

SELECT * FROM EmployeeDB.Employees
WHERE DEPARTMENT = 'IT';

UPDATE  LIBRARYDB.BOOKS
SET PRICE = PRICE * 0.5
WHERE  CATEGORY='Technology' ;

SELECT * FROM LIBRARYDB.BOOKS
WHERE  CATEGORY='Technology' ;

UPDATE  HOTELDB.ROOMS
SET Availability = 'Available'
WHERE PRICEPERDAY < 3000;

SELECT * FROM HOTELDB.ROOMS
WHERE PRICEPERDAY < 3000;

UPDATE SHOPPINGDB.PRODUCTS
SET DISCOUNT =  '10%'
WHERE PRICE> 5000;

SELECT * FROM SHOPPINGDB.PRODUCTS
WHERE PRICE> 5000;

update MOVIEDB.MOVIES
set Rating = 5.0
where GENRE = 'Drama';

SELECT * FROM MOVIEDB.MOVIES
where GENRE = 'Drama';

-- DELETE SINGLE RECORD

DELETE FROM StudentDB.students
WHERE StudentID = 110;

SELECT * FROM StudentDB.students
WHERE StudentID = 110;

DELETE FROM  EmployeeDB.Employees
WHERE EmployeeID = 210;

SELECT * FROM EmployeeDB.Employees
WHERE EmployeeID = 210;

DELETE FROM HOSPITALDB.PATIENTS
WHERE PatientID = 310;

SELECT * FROM HOSPITALDB.PATIENTS
WHERE PatientID = 310;

DELETE FROM  LIBRARYDB.BOOKS
WHERE BookID = 410;

SELECT * FROM LIBRARYDB.BOOKS
WHERE BookID = 410;

DELETE FROM SHOPPINGDB.PRODUCTS
WHERE ProductID = 510;

SELECT * FROM  SHOPPINGDB.PRODUCTS
WHERE ProductID = 510;

-- DELETE - USING CONDITION

DELETE FROM StudentDB.students
WHERE AGE < 18;

SELECT * FROM StudentDB.students
WHERE AGE < 18;

DELETE FROM  EmployeeDB.Employees
WHERE SALARY < 25000;

SELECT * FROM EmployeeDB.Employees
WHERE SALARY < 25000;

DELETE FROM HOSPITALDB.PATIENTS
WHERE DISEASE = 'FLUE';

SELECT * FROM HOSPITALDB.PATIENTS
WHERE DISEASE = 'FLUE';

DELETE FROM  LIBRARYDB.BOOKS
WHERE PRICE < 200;

SELECT * FROM LIBRARYDB.BOOKS
WHERE PRICE < 200;

DELETE FROM SHOPPINGDB.PRODUCTS
WHERE STOCKQUANTITY = 0;

SELECT * FROM  SHOPPINGDB.PRODUCTS
WHERE STOCKQUANTITY = 0;

-- DELETE - MULTIPLE CONDITION

DELETE FROM StudentDB.students
WHERE AGE > 25 AND DEPARTMENT = 'Mechanical';

SELECT * FROM  StudentDB.students
WHERE AGE > 25 AND DEPARTMENT = 'Mechanical';

DELETE FROM  EmployeeDB.Employees
WHERE SALARY < 30000 AND DEPARTMENT = 'HR';

SELECT * FROM EmployeeDB.Employees
WHERE SALARY < 30000 AND DEPARTMENT = 'HR';

DELETE FROM HOTELDB.ROOMS
WHERE Availability = 'Unavailable' AND PRICEPERDAY < 2000;

SELECT * FROM HOTELDB.ROOMS
WHERE Availability = 'Unavailable' AND PRICEPERDAY < 2000;

DELETE FROM MOVIEDB.MOVIES
WHERE LANGUAGE = 'TAMIL' AND RATING < 3.0;

SELECT * FROM MOVIEDB.MOVIES
WHERE LANGUAGE = 'TAMIL' AND RATING < 3.0;

DELETE FROM ECOMMERCEDB.CUSTOMERS
WHERE CITY = 'CHENNAI' AND COUNTRY = NULL;

SELECT * FROM ECOMMERCEDB.CUSTOMERS
WHERE CITY = 'CHENNAI' AND COUNTRY = NULL;
