-- ORDER BY COLUMN POSITION


SELECT STUDENTNAME, AGE, DEPARTMENT FROM StudentDB.STUDENTS ORDER BY 1 ASC;

SELECT STUDENTNAME, AGE, MARKS FROM StudentDB.STUDENTS ORDER BY 3 DESC;

SELECT EMPLOYEENAME, DEPARTMENT, SALARY
FROM EmployeeDB.EMPLOYEES
ORDER BY 3 DESC;

SELECT EMPLOYEENAME, SALARY, JOBROLE
FROM EmployeeDB.EMPLOYEES
ORDER BY 2 ASC;

SELECT PRODUCTNAME, PRICE, STOCK
FROM EmployeeDB.PRODUCTS
ORDER BY 2 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE
FROM EmployeeDB.PRODUCTS
ORDER BY 3 ASC;

SELECT BOOKNAME, AUTHOR, PRICE
FROM LibraryDB.BOOKS
ORDER BY 3 DESC;

SELECT BOOKNAME, CATEGORY, PRICE
FROM LibraryDB.BOOKS
ORDER BY 2 ASC;

SELECT COURSENAME, DURATION, FEES
FROM CollegeDB.COURSES
ORDER BY 3 DESC;

SELECT CUSTOMERNAME, CITY, AGE
FROM ECommerceDB.CUSTOMERS
ORDER BY 2 ASC;

SELECT CUSTOMERNAME, CITY, AGE
FROM ECommerceDB.CUSTOMERS
ORDER BY 3 DESC;

SELECT PATIENTNAME, AGE, BLOOD_GROUP
FROM ECommerceDB.PATIENTS
ORDER BY 2 ASC;

SELECT MOVIENAME, LANGUAGE, RATING
FROM ECommerceDB.MOVIES
ORDER BY 3 DESC;

SELECT EMPLOYEENAME, SALARY, EXPERIENCE
FROM ECommerceDB.EMPLOYEES
ORDER BY 2 DESC;

SELECT STUDENTNAME, DEPARTMENT, MARKS
FROM ECommerceDB.STUDENTS
ORDER BY 3 DESC;

SELECT PRODUCTNAME, BRAND, PRICE, STOCK
FROM ShoppingDB.PRODUCTS
ORDER BY 3 DESC;

SELECT BOOKNAME, AUTHOR, CATEGORY, PRICE
FROM ECommerceDB.BOOKS
ORDER BY 4 DESC;

SELECT COURSENAME, DEPARTMENT, DURATION, FEES
FROM ShoppingDB.COURSES
ORDER BY 4 DESC;

SELECT CUSTOMERNAME, CITY, EMAIL, PHONE
FROM ECommerceDB.CUSTOMERS
ORDER BY 2 ASC;

SELECT EMPLOYEENAME, DEPARTMENT, JOBROLE, SALARY
FROM EmployeeDB.EMPLOYEES
ORDER BY 4 DESC

-- MULTIPLE COLUMN POSITIONS 

SELECT EMPLOYEENAME, DEPARTMENT, SALARY
FROM EmployeeDB.EMPLOYEES
ORDER BY 2 ASC, 3 DESC;

SELECT STUDENTNAME, DEPARTMENT, MARKS
FROM EmployeeDB.STUDENTS
ORDER BY 2 ASC, 3 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE, STOCK
FROM ShoppingDB.PRODUCTS
ORDER BY 2 ASC, 3 DESC;

SELECT BOOKNAME, CATEGORY, PRICE, AUTHOR
FROM LibraryDB.BOOKS
ORDER BY 2 ASC, 3 DESC;

SELECT COURSENAME, DEPARTMENT, FEES, DURATION
FROM CollegeDB.COURSES
ORDER BY 2 ASC, 3 DESC;

SELECT CUSTOMERNAME, CITY, AGE
FROM ECommerceDB.CUSTOMERS
ORDER BY 2 ASC, 3 DESC;

SELECT EMPLOYEENAME, JOBROLE, DEPARTMENT, SALARY
FROM ECommerceDB.EMPLOYEES
ORDER BY 3 ASC, 4 DESC;

SELECT PRODUCTNAME, BRAND, CATEGORY, PRICE
FROM ShoppingDB.PRODUCTS
ORDER BY 2 ASC, 4 DESC;

SELECT STUDENTNAME, DEPARTMENT, AGE, MARKS
FROM StudentDB.STUDENTS
ORDER BY 2 ASC, 4 DESC;

SELECT BOOKNAME, AUTHOR, CATEGORY, PRICE
FROM LibraryDB.BOOKS
ORDER BY 3 ASC, 4 DESC;

SELECT EMPLOYEENAME, DEPARTMENT, SALARY, EXPERIENCE
FROM EmployeeDB.EMPLOYEES
ORDER BY 2 ASC, 3 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE, STOCK
FROM EmployeeDB.PRODUCTS
ORDER BY 2 ASC, 4 DESC;

SELECT COURSENAME, DEPARTMENT, DURATION, FEES
FROM CollegeDB.COURSES
ORDER BY 2 ASC, 4 DESC;

SELECT CUSTOMERNAME, CITY, AGE, EMAIL
FROM ECommerceDB.CUSTOMERS
ORDER BY 2 ASC, 3 DESC;

SELECT PATIENTNAME, BLOOD_GROUP, AGE, DISEASE
FROM HospitalDB.PATIENTS
ORDER BY 2 ASC, 3 DESC;

SELECT MOVIENAME, LANGUAGE, GENRE, RATING
FROM HospitalDB.MOVIES
ORDER BY 2 ASC, 4 DESC;

SELECT EMPLOYEENAME, DEPARTMENT, JOBROLE, SALARY, EXPERIENCE
FROM EmployeeDB.EMPLOYEES
ORDER BY 2 ASC, 4 DESC;

SELECT PRODUCTNAME, BRAND, CATEGORY, PRICE, STOCK
FROM ShoppingDB.PRODUCTS
ORDER BY 3 ASC, 4 DESC;

SELECT STUDENTNAME, DEPARTMENT, AGE, MARKS, ATTENDANCE
FROM ShoppingDB.STUDENTS
ORDER BY 2 ASC, 4 DESC;

SELECT COURSENAME, DEPARTMENT, FEES, DURATION, MODE
FROM ECommerceDB.COURSES
ORDER BY 2 ASC, 3 DESC;

-- C. ORDER BY POSITION WITH EXPRESSIONS 

SELECT EMPLOYEENAME, SALARY * 12
FROM EmployeeDB.EMPLOYEES
ORDER BY 2 DESC;

SELECT PRODUCTNAME, PRICE * QUANTITY
FROM ShoppingDB.PRODUCTS
ORDER BY 2 DESC;

SELECT EMPLOYEENAME, SALARY * 1.10
FROM EmployeeDB.EMPLOYEES
ORDER BY 2 DESC;

SELECT PRODUCTNAME, PRICE * 0.90
FROM ShoppingDB.PRODUCTS
ORDER BY 2 ASC;

SELECT STUDENTNAME, LENGTH(STUDENTNAME)
FROM StudentDB.STUDENTS
ORDER BY 2 DESC;

SELECT EMPLOYEENAME, SALARY / 12
FROM EmployeeDB.EMPLOYEES
ORDER BY 2 ASC;

SELECT PRODUCTNAME, PRICE * QUANTITY AS TOTAL_VALUE
FROM ShoppingDB.PRODUCTS
ORDER BY 2 DESC;

SELECT BOOKNAME, PRICE * 0.80 AS DISCOUNTED_PRICE
FROM LibraryDB.BOOKS
ORDER BY 2 ASC;

SELECT COURSENAME, FEES * 0.85 AS FINAL_FEES
FROM CollegeDB.COURSES
ORDER BY 2 DESC;

SELECT STUDENTNAME, AGE + 1 AS NEXT_YEAR_AGE
FROM StudentDB.STUDENTS
ORDER BY 2 ASC;

SELECT EMPLOYEENAME, DEPARTMENT, SALARY * 12 AS ANNUAL_SALARY
FROM EmployeeDB.EMPLOYEES
ORDER BY 3 DESC;

SELECT PRODUCTNAME, CATEGORY, PRICE * STOCK AS TOTAL_STOCK_VALUE
FROM ShoppingDB.PRODUCTS
ORDER BY 3 DESC;

SELECT STUDENTNAME, DEPARTMENT, LENGTH(STUDENTNAME) AS NAME_LENGTH
FROM StudentDB.STUDENTS
ORDER BY 3 DESC;

SELECT BOOKNAME, CATEGORY, PRICE * 0.80 AS DISCOUNTED_PRICE
FROM LibraryDB.BOOKS
ORDER BY 3 ASC;

SELECT COURSENAME, DEPARTMENT, FEES * 0.85 AS FINAL_FEES
FROM CollegeDB.COURSES
ORDER BY 3 DESC;

SELECT EMPLOYEENAME, SALARY, SALARY * 12 AS ANNUAL_SALARY
FROM CollegeDB.EMPLOYEES
ORDER BY 3 DESC;

SELECT PRODUCTNAME, PRICE, QUANTITY, PRICE * QUANTITY AS TOTAL_VALUE
FROM ShoppingDB.PRODUCTS
ORDER BY 4 DESC;

SELECT STUDENTNAME, MARKS, ATTENDANCE, (MARKS + ATTENDANCE) / 2 AS AVERAGE_SCORE
FROM StudentDB.STUDENTS
ORDER BY 4 DESC;

SELECT EMPLOYEENAME, SALARY, EXPERIENCE, SALARY * 12 AS YEARLY_PAY
FROM EmployeeDB.EMPLOYEES
ORDER BY 4 DESC;

SELECT PRODUCTNAME, PRICE, STOCK, PRICE * STOCK AS INVENTORY_VALUE
FROM ShoppingDB.PRODUCTS
ORDER BY 4 DESC;

-- ORDER BY POSITION WITH AGGREGATE FUNCTIONS 

SELECT DEPARTMENT, COUNT(*)
FROM EmployeeDB.EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, SUM(SALARY)
FROM EmployeeDB.EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, MAX(SALARY)
FROM EmployeeDB.EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, MIN(SALARY)
FROM EmployeeDB.EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 ASC;

SELECT CATEGORY, COUNT(*)
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, AVG(PRICE)
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 ASC;

SELECT CATEGORY, MAX(PRICE)
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, MIN(PRICE)
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 ASC;

SELECT CATEGORY, SUM(PRICE * QUANTITY)
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT, AVG(SALARY) AS AVERAGE_SALARY
FROM EmployeeDB.EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC;

SELECT DEPARTMENT, COUNT(*) AS EMPLOYEE_COUNT, AVG(SALARY) AS AVERAGE_SALARY
FROM EmployeeDB.EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 3 DESC;

SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT, SUM(STOCK) AS TOTAL_STOCK
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, COUNT(*) AS PRODUCT_COUNT, SUM(STOCK) AS TOTAL_STOCK
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 3 DESC;

SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY, MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 ASC;

SELECT DEPARTMENT, MIN(SALARY) AS MINIMUM_SALARY, MAX(SALARY) AS MAXIMUM_SALARY
FROM EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 3 DESC;

SELECT CATEGORY, AVG(PRICE) AS AVERAGE_PRICE, MAX(PRICE) AS MAXIMUM_PRICE
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC;

SELECT CATEGORY, AVG(PRICE) AS AVERAGE_PRICE, MAX(PRICE) AS MAXIMUM_PRICE
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 3 DESC;

SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY, COUNT(*) AS EMPLOYEE_COUNT
FROM ShoppingDB.EMPLOYEES
GROUP BY DEPARTMENT
ORDER BY 2 DESC, 3 ASC;

SELECT CATEGORY, SUM(PRICE * STOCK) AS TOTAL_VALUE, COUNT(*) AS PRODUCT_COUNT
FROM ShoppingDB.PRODUCTS
GROUP BY CATEGORY
ORDER BY 2 DESC, 3 DESC;

