-- ANY
SELECT * FROM EmployeeDB.Employees WHERE SALARY > ANY (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'HR');
SELECT * FROM EmployeeDB.Employees WHERE SALARY < ANY (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'IT');
SELECT * FROM EmployeeDB.Employees WHERE SALARY = ANY (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'FINANCE');
SELECT * FROM ShoppingDB.Products WHERE PRICE > ANY(SELECT PRICE FROM  ShoppingDB.Products WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM ShoppingDB.Products WHERE PRICE < ANY(SELECT PRICE FROM  ShoppingDB.Products WHERE CATEGORY = 'ACCESSORIES');
SELECT * FROM LibraryDB.Books WHERE PRICE > ANY (SELECT PRICE FROM LibraryDB.Books WHERE CATEGORY ='TECHNOLOGY');
SELECT * FROM LibraryDB.Books WHERE PRICE < ANY (SELECT PRICE FROM LibraryDB.Books WHERE CATEGORY = 'SCIENCE');
SELECT * FROM StudentDB.students WHERE AGE > ANY (SELECT AGE FROM StudentDB.students WHERE DEPARTMENT = 'IT');
SELECT * FROM StudentDB.students WHERE AGE < ANY (SELECT AGE FROM StudentDB.students WHERE DEPARTMENT = 'CSE');
SELECT * FROM CollegeDB.Courses WHERE FEES > ANY ( SELECT FEES FROM CollegeDB.Courses WHERE DEPARTMENT = 'IT');
SELECT * FROM CollegeDB.Courses WHERE FEES < ANY ( SELECT FEES FROM CollegeDB.Courses WHERE DEPARTMENT = 'CSE');
SELECT * FROM EmployeeDB.Employees WHERE SALARY > ANY (SELECT SALARY FROM EmployeeDB.Employees WHERE DESIGNATION = 'DEVELOPER');
SELECT * FROM ShoppingDB.Products WHERE PRICE > ANY(SELECT PRICE FROM  ShoppingDB.Products WHERE BRAND = 'SAMSUNG');
SELECT * FROM LibraryDB.Books WHERE QUANTITY > ANY (SELECT QUANTITY FROM LibraryDB.Books WHERE CATEGORY = 'TECHNOLOGY');
SELECT * FROM HospitalDB.Patients where AGE > ANY (SELECT AGE FROM HospitalDB.Patients where DISEASE = 'FEVER');
-- ALL
SELECT * FROM EmployeeDB.Employees WHERE SALARY > ALL (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'HR');
SELECT * FROM EmployeeDB.Employees WHERE SALARY < ALL (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'IT');
SELECT * FROM EmployeeDB.Employees WHERE SALARY = ALL (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'FINANCE');
SELECT * FROM ShoppingDB.Products WHERE PRICE > ALL(SELECT PRICE FROM  ShoppingDB.Products WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM ShoppingDB.Products WHERE PRICE < ALL(SELECT PRICE FROM  ShoppingDB.Products WHERE CATEGORY = 'ACCESSORIES');
SELECT * FROM LibraryDB.Books WHERE PRICE > ALL (SELECT PRICE FROM LibraryDB.Books WHERE CATEGORY ='TECHNOLOGY');
SELECT * FROM LibraryDB.Books WHERE PRICE < ALL (SELECT PRICE FROM LibraryDB.Books WHERE CATEGORY = 'SCIENCE');
SELECT * FROM StudentDB.students WHERE AGE > ALL (SELECT AGE FROM StudentDB.students WHERE DEPARTMENT = 'IT');
SELECT * FROM StudentDB.students WHERE AGE < ALL (SELECT AGE FROM StudentDB.students WHERE DEPARTMENT = 'CSE');
SELECT * FROM CollegeDB.Courses WHERE FEES > ALL ( SELECT FEES FROM CollegeDB.Courses WHERE DEPARTMENT = 'IT');
SELECT * FROM CollegeDB.Courses WHERE FEES < ALL ( SELECT FEES FROM CollegeDB.Courses WHERE DEPARTMENT = 'CSE');
SELECT * FROM EmployeeDB.Employees WHERE SALARY > ALL (SELECT SALARY FROM EmployeeDB.Employees WHERE DESIGNATION = 'DEVELOPER');
SELECT * FROM ShoppingDB.Products WHERE PRICE > ALL(SELECT PRICE FROM  ShoppingDB.Products WHERE BRAND = 'SAMSUNG');
SELECT * FROM LibraryDB.Books WHERE QUANTITY > ALL (SELECT QUANTITY FROM LibraryDB.Books WHERE CATEGORY = 'TECHNOLOGY');
SELECT * FROM HospitalDB.Patients where AGE > ALL (SELECT AGE FROM HospitalDB.Patients where DISEASE = 'FEVER');
-- MIXED ANY AND ALL
SELECT * FROM EmployeeDB.Employees WHERE SALARY > ANY (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'HR');
SELECT * FROM EmployeeDB.Employees WHERE SALARY > ALL (SELECT SALARY FROM EmployeeDB.Employees WHERE DEPARTMENT = 'HR');
SELECT * FROM ShoppingDB.Products WHERE PRICE < ANY(SELECT PRICE FROM  ShoppingDB.Products WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM ShoppingDB.Products WHERE PRICE < ALL(SELECT PRICE FROM  ShoppingDB.Products WHERE CATEGORY = 'ELECTRONICS');
SELECT * FROM LibraryDB.Books WHERE PRICE > ANY (SELECT PRICE FROM LibraryDB.Books WHERE CATEGORY ='TECHNOLOGY');
SELECT * FROM LibraryDB.Books WHERE PRICE > ALL (SELECT PRICE FROM LibraryDB.Books WHERE CATEGORY ='TECHNOLOGY');
SELECT * FROM StudentDB.students WHERE AGE > ANY (SELECT AGE FROM StudentDB.students WHERE DEPARTMENT = 'CSE');
SELECT * FROM StudentDB.students WHERE AGE > ALL (SELECT AGE FROM StudentDB.students WHERE DEPARTMENT = 'CSE');
SELECT * FROM EmployeeDB.Employees WHERE SALARY < any (SELECT SALARY FROM EmployeeDB.Employees WHERE DESIGNATION = 'DEVELOPER');
SELECT * FROM EmployeeDB.Employees WHERE SALARY < ALL (SELECT SALARY FROM EmployeeDB.Employees WHERE DESIGNATION = 'DEVELOPER');



