-- STRING SCALAR FUNCTIONS 

SELECT UPPER(STUDENTNAME) FROM StudentDB.STUDENTS;
SELECT LOWER(EMPLOYEENAME) FROM EmployeeDB.EMPLOYEES;
SELECT LENGTH(STUDENTNAME) FROM StudentDB.STUDENTS;
SELECT EMPLOYEENAME, LEFT(EMPLOYEENAME, 3) AS FIRST_THREE FROM EmployeeDB.EMPLOYEES;
SELECT STUDENTNAME, RIGHT(STUDENTNAME, 3) AS LAST_THREE FROM StudentDB.STUDENTS;
SELECT SUBSTRING(PRODUCTNAME,1,6) FROM ShoppingDB.PRODUCTS;
SELECT RIGHT(TITLE,4) FROM LibraryDB.BOOKS;
SELECT CONCAT(FIRST_NAME, LAST_NAME) AS FULL_NAME FROM StudentDB.STUDENTS;
SELECT CONCAT(EMPLOYEENAME, DEPARTMENT) AS COMBINED_COLUMN FROM EmployeeDB.EMPLOYEES;
SELECT CONCAT(PRODUCTNAME, BRAND) AS COMBINED_COLUMN FROM ShoppingDB.PRODUCTS;
SELECT TRIM(STUDENTNAME) AS TRIMED_NAME FROM StudentDB.STUDENTS;
SELECT SUBSTRING(EMPLOYEENAME,1,4) AS FIRST_4_CHAR FROM EmployeeDB.EMPLOYEES;
SELECT SUBSTRING(PRODUCTNAME, 2,5) AS CHARACTERS FROM ShoppingDB.PRODUCTS;
SELECT STUDENTNAME, UPPER(STUDENTNAME) AS UPPER_NAME, LENGTH(STUDENTNAME) AS LENGHT FROM StudentDB.STUDENTS;
SELECT EMPLOYEENAME, LOWER(EMPLOYEENAME) AS LOWER_NAME, LENGTH(EMPLOYEENAME) AS LENGTH FROM EmployeeDB.EMPLOYEES;
SELECT CONCAT(FIRST_NAME, CITY) AS COMBINED_NAME FROM ECommerceDB.CUSTOMERS;
SELECT CONCAT(TITLE,' - ' , CATEGORY) AS COMBINED_COLUMN FROM LibraryDB.BOOKS;
SELECT CONCAT(EMPLOYEENAME,' - ', DESIGNATION) AS COMBINED_COLUMN FROM EmployeeDB.EMPLOYEES;
SELECT UPPER(PRODUCTNAME) AS UPPER_NAME, LOWER(BRAND) AS BRAND_NAME FROM ShoppingDB.PRODUCTS;
SELECT LEFT(STUDENTNAME,1) AS FIRST_CHAR, RIGHT(STUDENTNAME,1) AS LAST_CHAR FROM StudentDB.STUDENTS;

-- NUMERIC SCALAR FUNCTIONS

SELECT ROUND(SALARY,2) FROM EmployeeDB.EMPLOYEES;
SELECT ROUND(PRICE,2) FROM ShoppingDB.PRODUCTS;
SELECT ROUND(FEES,-2) FROM CollegeDB.COURSES;
SELECT CEIL(PRICE) FROM ShoppingDB.PRODUCTS;
SELECT FLOOR(PRICE) FROM ShoppingDB.PRODUCTS;
SELECT ABS(SALARY-50000) AS REMAINING FROM EmployeeDB.EMPLOYEES;
SELECT MOD(PRICE,1000) AS REMAINDER FROM ShoppingDB.PRODUCTS;
SELECT SALARY*12 AS ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY*1.10 AS INCREMENT FROM EmployeeDB.EMPLOYEES;
SELECT PRICE*0.85 AS DISCOUNT_PRICE FROM ShoppingDB.PRODUCTS;
SELECT PRICE*0.90 AS DOSCOUNTED_PRICE FROM ShoppingDB.PRODUCTS;
SELECT POWER(AGE,2) AS SQUARE FROM StudentDB.STUDENTS;
SELECT POWER(QUANTITY,3) AS CUBEVALUE FROM ShoppingDB.PRODUCTS;
SELECT ABS(PRICE-10000) AS DIFFERENCE FROM ShoppingDB.PRODUCTS;
SELECT CEIL(FEES) AS COURSE_FEES FROM CollegeDB.COURSES;
SELECT FLOOR(PRICE) AS PRICE FROM ShoppingDB.PRODUCTS;
SELECT MOD(SALARY,10000) AS REMAINDER FROM EmployeeDB.EMPLOYEES;
SELECT PRICE*QUANTITY AS TOTA_VALUE FROM ShoppingDB.PRODUCTS;
SELECT SALARY*12 AS ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT ROUND(SALARY*1.10,2) AS INCREMENT_ROUNDOFF FROM EmployeeDB.EMPLOYEES;

-- DATE & TIME SCALAR FUNCTIONS 

SELECT CURRENT_DATE() AS DATE;
SELECT CURRENT_TIME() AS TIME_NOW;
SELECT CURRENT_TIMESTAMP() AS CURRENT_DATE_TIME;
SELECT NOW() AS CURRENT_DATE_TIME;
SELECT YEAR(JOINING_DATE) AS YEAR;
SELECT MONTH(JOINING_DATE) AS MONTH;
SELECT DAY(JOINING_DATE) AS DAY;
SELECT YEAR(REGISTRATION_DATE) AS CUSTOMERYEAR;
SELECT MONTH(REGISTRATION_DATE) AS CUSTOMERMONTH;
SELECT DAY(REGISTRATION_DATE) AS CUSTOMERDAY;
SELECT DATE_ADD(JOIN_DATE,INTERVAL 30 DAY ) AS FUTURE_DATE FROM EmployeeDB.EMPLOYEES;
SELECT DATE_ADD(JOIN_DATE, INTERVAL 90 DAY) AS FUTURE_DATE FROM EmployeeDB.EMPLOYEES;
SELECT DATE_SUB(JOIN_DATE, INTERVAL 42 DAY) AS BEFORE_DATE FROM EmployeeDB.EMPLOYEES;
SELECT DATE_ADD(REGISTRATION_DATE,INTERVAL 126 DAY) FUTURE_DATE FROM ECommerceDB.CUSTOMERS;
SELECT DATE_SUB(REGISTRATION_DATE,INTERVAL 30 DAY) BEFORE_DATE FROM ECommerceDB.CUSTOMERS;
SELECT DATE_FORMAT(JOINING_DATE,'DD-MM-YYYY') AS JOIN_DATE FROM EmployeeDB.EMPLOYEES;
SELECT DATE_FORMAT(REGISTRATION_DATE, 'MM/DD/YYYY') AS REG_DATE FROM ECommerceDB,CUSTOMERS;
SELECT DATE_FORMAT(MANUFACTURING_DATE, 'YYYY-MM-DD') AS MANUFACTING_DATE FROM ShoppingDB.PRODUCTS;
SELECT YEAR(JOINING_DATE) AS YEAR, MONTH(JOINING_DATE) AS MONTH FROM EmployeeDB.EMPLOYEES;
SELECT DATE_DIFF(REGISTRATION_DATE, JOINING_DATE) AS DATE_DIFFERENCE FROM ECommerceDB.CUSTOMERS;

-- NULL-HANDLING SCALAR FUNCTIONS 

SELECT IFNULL(EMAIL, 'NOT AVAILABLE') AS EMAIL FROM StudentDB.STUDENTS;
SELECT IFNULL(PHONE_NUMBER, 'NO PHONE') AS PHONE_NUMBER FROM EmployeeDB.EMPLOYEES;
SELECT IFNULL(BRAND, 'UNKNOWN BRAND') AS BRAND FROM ShoppingDB.PRODUCTS;
SELECT IFNULL(AUTHOR, 'UNKNOWN AUTHOR') AS AUTHOR FROM LibraryDB.BOOKS;
SELECT IFNULL(EMAIL, 'EMAIL MISSING') AS EMAIL FROM ECommerceDB.CUSTOMERS;
SELECT IFNULL(DEPARTMENT, 'NOT ASSIGNED') AS DEPARTMENT FROM EMPLOYEES;
SELECT IFNULL(DISCOUNT, 0) AS DISCOUNT FROM ShoppingDB.PRODUCTS;
SELECT IFNULL(FEES, 0) AS FEES FROM CollegeDB.COURSES;
SELECT IFNULL(DISEASE, 'NOT SPECIFIED') AS DISEASE FROM HospitalDB.PATIENTS;
SELECT COALESCE(PHONE_NUMBER, 'NO PHONE') AS PHONE_NUMBER FROM StudentDB.STUDENTS;
SELECT COALESCE(EMAIL, 'NO EMAIL') AS EMAIL FROM EmployeeDB.EMPLOYEES;
SELECT COALESCE(BRAND, 'NO BRAND') AS BRAND FROM ShoppingDB.PRODUCTS;
SELECT COALESCE(PHONE_NUMBER, EMAIL, ALTERNATE_PHONE) AS CONTACT_DETAILS FROM ECommerceDB.CUSTOMERS;
SELECT IFNULL(DURATION, 'DURATION NOT AVAILABLE') AS DURATION FROM CollegeDB.COURSES;
SELECT IFNULL(PUBLICATION_YEAR, 'YEAR UNKNOWN') AS PUBLICATION_YEAR FROM LibraryDB.BOOKS;

-- CONDITIONAL SCALAR FUNCTIONS 

SELECT EMPLOYEENAME, IF(SALARY >= 60000, 'HIGH', 'LOW') AS SALARY_STATUS FROM EmployeeDB.EMPLOYEES;
SELECT STUDENTNAME, IF(MARKS >= 40, 'PASS', 'FAIL') AS RESULT FROM StudentDB.STUDENTS;
SELECT PRODUCTNAME, IF(STOCK > 0, 'AVAILABLE', 'OUT OF STOCK') AS STOCK_STATUS FROM ShoppingDB.PRODUCTS;
SELECT EMPLOYEENAME, IF(EXPERIENCE >= 5, 'EXPERIENCED', 'FRESHER') AS EXPERIENCE_STATUS FROM EmployeeDB.EMPLOYEES;
SELECT COURSENAME, IF(FEES > 50000, 'EXPENSIVE', 'AFFORDABLE') AS COURSE_STATUS FROM CollegeDB.COURSES;
SELECT TITLE, IF(PRICE >= 1000, 'PREMIUM', 'REGULAR') AS BOOK_STATUS FROM LibraryDB.BOOKS;
SELECT CUSTOMERNAME, IF(AGE >= 18, 'ADULT', 'MINOR') AS CUSTOMER_STATUS FROM ECommerceDB.CUSTOMERS;
SELECT PRODUCTNAME, IF(STOCK < 10, 'LOW STOCK', 'SUFFICIENT STOCK') AS STOCK_STATUS FROM ShoppingDB.PRODUCTS;
SELECT EMPLOYEENAME, IF(SALARY >= 50000, 'ELIGIBLE', 'NOT ELIGIBLE') AS ELIGIBILITY_STATUS FROM EmployeeDB.EMPLOYEES;
SELECT STUDENTNAME, IF(ATTENDANCE >= 75, 'ELIGIBLE', 'NOT ELIGIBLE') AS ELIGIBILITY_STATUS FROM StudentDB.STUDENTS;

-- MIXED SCALAR FUNCTION QUESTIONS

SELECT STUDENTNAME, IF(ATTENDANCE >= 75, 'ELIGIBLE', 'NOT ELIGIBLE') AS ELIGIBILITY_STATUS FROM StudentDB.STUDENTS;
SELECT UPPER(EMPLOYEENAME) AS EMPLOYEE_NAME, ROUND(SALARY,2) AS SALARY FROM EmployeeDB.EMPLOYEES;
SELECT LOWER(PRODUCTNAME) AS PRODUCT_NAME, PRICE*0.90 AS DISCOUNTED_PRICE FROM ShoppingDB.PRODUCTS;
SELECT UPPER(STUDENTNAME) AS STUDENT_NAME, LEN(STUDENTNAME) AS NAME_LENGTH FROM StudentDB.STUDENTS;
SELECT EMPLOYEENAME, SALARY*12 AS ANNUAL_SALARY, ROUND(SALARY*12,2) AS ROUNDED_ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT PRODUCTNAME, PRICE, PRICE*0.18 AS GST_AMOUNT, PRICE+(PRICE*0.18) AS FINAL_PRICE FROM ShoppingDB.PRODUCTS;
SELECT CUSTOMERNAME, YEAR(REGISTRATION_DATE) AS REGISTRATION_YEAR FROM ECommerceDB.CUSTOMERS;
SELECT EMPLOYEENAME, MONTH(JOINING_DATE) AS JOINING_MONTH FROM EmployeeDB.EMPLOYEES;
SELECT UPPER(TITLE) AS BOOK_NAME, ROUND(PRICE,2) AS PRICE FROM LibraryDB.BOOKS;
SELECT PRODUCTNAME, PRICE*QUANTITY AS TOTAL_STOCK_VALUE FROM ShoppingDB.PRODUCTS;
SELECT EMPLOYEENAME, SALARY*1.10 AS INCREMENTED_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT STUDENTNAME, AGE, POWER(AGE,2) AS AGE_SQUARED FROM StudentDB.STUDENTS;
SELECT PRODUCTNAME, MOD(PRICE,1000) AS REMAINDER FROM ShoppingDB.PRODUCTS;
SELECT CUSTOMERNAME, DATE_ADD(REGISTRATION_DATE,INTERVAL 30 DAY) AS REGISTRATION_DATE_AFTER_30_DAYS FROM ECommerceDB.CUSTOMERS;
SELECT EMPLOYEENAME, IFNULL(DEPARTMENT,'NOT ASSIGNED') AS DEPARTMENT FROM EmployeeDB.EMPLOYEES;
SELECT UPPER(PRODUCTNAME) AS PRODUCT_NAME, ROUND(PRICE,2) AS PRICE, IFNULL(BRAND,'UNKNOWN') AS BRAND FROM ShoppingDB.PRODUCTS;