-- Statistical / Aggregate Functions
SELECT COUNT(*) FROM EmployeeDB.Employees ;
SELECT SUM(SALARY) FROM EmployeeDB.Employees;
SELECT AVG(SALARY) FROM EmployeeDB.Employees;
SELECT MAX(SALARY) FROM EmployeeDB.Employees;
SELECT MIN(SALARY) FROM EmployeeDB.Employees;
SELECT COUNT(*) FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT AVG(MARKS) FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT MIN(MARKS) AS LOWEST_MARKS, MAX(MARKS) AS HIGHEST_MARKS FROM StudentDB.students GROUP BY DEPARTMENT;
SELECT SUM(SALES) FROM  ECommerceDB.Customers;
SELECT category,AVG(PRICE) FROM ShoppingDB.Products GROUP BY CATEGORY;
-- Challenges question
SELECT EMPLOYEENAME,SALARY, SALARY * 12 AS ANNUAL_SALARY FROM EmployeeDB.Employees ORDER BY salary DESC LIMIT 5;
SELECT UPPER(EMPLOYEENAME) AS EMPLOYEE_NAME,LENGTH(EMPLOYEENAME) AS NAME_LENGTH FROM EMPLOYEEDB.EMPLOYEES ORDER BY NAME_LENGTH DESC;
SELECT productname, ROUND(price, 2) AS rounded_price FROM ShoppingDB.Products ORDER BY price DESC;
SELECT * FROM ShoppingDB.Products ORDER BY price DESC LIMIT 10 OFFSET 10;
SELECT department, AVG(salary) AS average_salary FROM EmployeeDB.Employees GROUP BY department ORDER BY average_salary DESC LIMIT 1;