-- LIKE WITH %

SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE 'A%';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE '%a';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE '%an%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE 'R%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE '%N';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE '%RN%';
SELECT * FROM HospitalDB.Patients WHERE PATIENTNAME LIKE 'P%';
SELECT * FROM HospitalDB.Patients WHERE PATIENTNAME LIKE '%I';
SELECT * FROM HospitalDB.Patients WHERE DISEASE LIKE '%FEVER%'; 
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE 'S%';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE '%SQL';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE '%DATA%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE 'M%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE '%PHONE';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE '%BOOK%';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME LIKE 'K%';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME LIKE '%A';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CITY LIKE '%PUR%';
SELECT * FROM CollegeDB.Courses WHERE COURSENAME LIKE '%DATA%';
SELECT * FROM MovieDB.Movies WHERE TITLE LIKE 'THE%';

-- LIKE WITH _
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE '_____';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE '______';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE '_____';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE 'A____';
SELECT * FROM HospitalDB.Patients WHERE PATIENTNAME LIKE '____';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE '_____';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE '______';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME LIKE '_____';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE '_A%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE '_r%';
SELECT * FROM HospitalDB.Patients WHERE PATIENTNAME LIKE '__i%';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE '_o%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE '_a%';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME LIKE '_A%';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE 'Ak%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE 'R_H%';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE 'S_L%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE 'M__I%';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME LIKE 'K%A';
SELECT * FROM MovieDB.Movies WHERE TITLE LIKE '_______';

-- COMBAINING % AND _

SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE 'A_%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE 'R_H%';
SELECT * FROM HospitalDB.Patients WHERE PATIENTNAME LIKE 'P%A';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE 'S_%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE 'M%E';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME LIKE 'K%A';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE '_A%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE '_R%N';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE 'D%SQL%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE '%PHONE%';

-- NOT LIKE 
SELECT * FROM StudentDB.students WHERE STUDENTNAME NOT LIKE 'A%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME NOT LIKE '%N';
SELECT * FROM HospitalDB.Patients WHERE DISEASE NOT LIKE '%FEVER%'; 
SELECT * FROM LibraryDB.Books WHERE TITLE NOT LIKE 'S_%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME NOT LIKE '%PHONE%';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME NOT LIKE '%A';
SELECT * FROM CollegeDB.Courses WHERE COURSENAME NOT LIKE '%DATA%';
SELECT * FROM MovieDB.Movies WHERE TITLE NOT LIKE 'THE%';
SELECT * FROM StudentDB.students WHERE STUDENTNAME NOT LIKE '%AN%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME NOT LIKE 'R%';

-- LIKE WITH OTHER CONDITIONS
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE 'A%' AND AGE > 20;
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE 'R%' AND SALARY > 40000;
SELECT * FROM HospitalDB.Patients WHERE PATIENTNAME LIKE 'P%' AND AGE BETWEEN 20 AND 40;
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE '%SQL%' AND PRICE < 1000;
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE '%PHONE%' AND PRICE > 5000;
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CUSTOMERNAME LIKE 'K%' AND CITY = 'CHENNAI';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE 'A%' AND DEPARTMENT = 'IT';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE '%AR%' AND DEPARTMENT = 'IT';
SELECT * FROM ShoppingDB.Products WHERE BRAND LIKE 'S%' AND CATEGORY ='ELECTRONICS';
SELECT * FROM MovieDB.Movies WHERE TITLE LIKE 'M%' AND LANGUAGE = 'TAMIL';

-- MIXED LIKE AND WILDCARD 
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE 'A%A';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE 'S%R%';
SELECT * FROM HospitalDB.Patients WHERE PATIENTNAME LIKE '%RI%';
SELECT * FROM LibraryDB.Books WHERE TITLE LIKE '%DATA%';
SELECT * FROM ShoppingDB.Products WHERE PRODUCTNAME LIKE 'SMART%';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE CITY LIKE '%PUR';
SELECT * FROM CollegeDB.Courses WHERE COURSENAME LIKE 'DATA%SCIENCE%';
SELECT * FROM MovieDB.Movies WHERE TITLE LIKE '%LOVE%';
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEENAME LIKE 'A_____';
SELECT * FROM StudentDB.students WHERE STUDENTNAME LIKE '____A';