SELECT CURRENT_DATE();

SELECT CURRENT_TIME();

SELECT CURRENT_TIMESTAMP();

SELECT NOW();

SELECT DATE_FORMAT(CURRENT_DATE , '%d-%m-%Y') as `today's date`;

SELECT DATE_FORMAT(CURRENT_DATE , '%d/%m/%Y') as `today's date`;

SELECT DATE_FORMAT(CURRENT_DATE , '%M %D,%Y') as `today's date`;

SELECT TIME_FORMAT(CURRENT_TIME, '%H:%i:%S') AS `CURRENT_TIME`;

SELECT TIME_FORMAT(CURRENT_TIME, '%h:%i:%S %p') AS `CURRENT_TIME`;

SELECT CURRENT_DATE + INTERVAL 125 DAY AS FORWARD_DATE;

SELECT CURRENT_DATE - INTERVAL 42 DAY AS BACKWARD_DATE;

SELECT DATE_FORMAT(CURRENT_DATE + INTERVAL 90 DAY , '%d-%m-%Y') AS A;

SELECT DATE_FORMAT(CURRENT_DATE - INTERVAL 60 DAY , '%d-%m-%Y') AS B;

SELECT DATE_FORMAT(CURRENT_TIMESTAMP, '%d-%m-%Y %h:%i:%s') as C;

SELECT DATE_FORMAT(CURRENT_DATE, '%D-%M-%Y') AS D;