-- COLUMN ALIAS 

SELECT STUDENTNAME AS STUDNET_NAME FROM StudentDB.STUDENTS;
SELECT EMPLOYEENAME AS EMPLOYEE_NAME FROM EmployeeDB.EMPLOYEES;
SELECT SALARY AS MONTHLY_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT PRODUCTNAME AS PRODUCT_NAME FROM ShoppingDB.PRODUCTS;
SELECT PRICE AS PRODUCT_PRICE FROM ShoppingDB.PRODUCTS;
SELECT TITLE AS BOOK_NAME FROM LibraryDB.BOOKS;
SELECT COURSENAME AS COURSE_NAME FROM CollegeDB.COURSES;
SELECT CUSTOMERNAME AS CUSTOMER_NAME FROM ECommerceDB.CUSTOMERS;
SELECT DEPARTMENT AS DEPARTMENT_NAME FROM StudentDB.STUDENTS;
SELECT DESIGNATION AS JOB_ROLE FROM EmployeeDB.EMPLOYEES;
SELECT JOINING_DATE AS DATE_OF_JOINING FROM EmployeeDB.EMPLOYEES;
SELECT REGISTRATIONDATE AS REGISTRATION_DATE FROM ECommerceDB.CUSTOMERS;
SELECT STOCK AS AVAILABLE_STOCK FROM ShoppingDB.PRODUCTS;
SELECT FEES AS COURSE_FEES FROM CollegeDB.COURSES;
SELECT EMAIL AS EMAIL_ID FROM StudentDB.STUDENTS;
SELECT PHONE_NUMBER AS CONTACT_NUMBER FROM EmployeeDB.EMPLOYEES;
SELECT AUTHOR AS AUTHOR_NAME FROM LibraryDB.BOOKS;
SELECT BRAND AS BRAND_NAME FROM ShoppingDB.PRODUCTS;
SELECT BLOODGROUP AS BLOOD_GROUP FROM HospitalDB.PATIENTS;
SELECT RATING AS MOVIE_RATING FROM MovieDB.MOVIES;

-- ALIAS WITH EXPRESSIONS

SELECT SALARY*12 AS ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY*1.1 AS INCREMENTED_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SALARY*0.95 AS NET_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT PRICE*QUANTITY AS TOTAL_VALUE FROM ShoppingDB.PRODUCTS;
SELECT PRICE*0.9 AS DISCOUNTED_PRICE FROM ShoppingDB.PRODUCTS;
SELECT PRICE*1.18 AS FINAL_PRICE FROM ShoppingDB.PRODUCTS;
SELECT PRICE*0.8 AS DISCOUNTED_PRICE FROM LibraryDB.BOOKS;
SELECT FEES*0.85 AS FINAL_FEES FROM CollegeDB.COURSES;
SELECT AGE+1 AS NEXT_YEAR_AGE FROM StudentDB.STUDENTS;
SELECT SALARY/12 AS MONTHLY_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT PRICE*STOCK_QUANTITY AS STOCK_VALUE FROM ShoppingDB.PRODUCTS;
SELECT SALARY*12*1.10 AS ANNUAL_SALARY_AFTER_INCREMENT FROM EmployeeDB.EMPLOYEES;
SELECT LEN(STUDENT_NAME) AS NAME_LENGTH FROM StudentDB.STUDENTS;
SELECT UPPER(EMPLOYEENAME) AS UPPER_NAME FROM EmployeeDB.EMPLOYEES;
SELECT LOWER(PRODUCTNAME) AS LOWER_PRODUCT_NAME FROM ShoppingDB.PRODUCTS;
SELECT CONCAT(FIRSTNAME , LASTNAME) AS FULL_NAME FROM StudentDB.STUDENTS;
SELECT DATE_ADD(DATE_OF_JOINING,INTERVAL 126 DAY) AS FUTURE_DATE FROM EmployeeDB.EMPLOYEES;
SELECT DATE_SUB(DATE_OF_JOINING,INTERVAL 42 DAY) AS PREVIOUS_DATE FROM EmployeeDB.EMPLOYEES;
SELECT (SALARY - 50000) AS SALARY_DIFFERENCE FROM EmployeeDB.EMPLOYEES; 
SELECT ROUND(PRICE,2) AS ROUNDED_PRICE FROM ShoppingDB.PRODUCT;

-- ALIAS WITH AGGREGATE FUNCTIONS 

SELECT COUNT(*) AS TOTAL_STUDENTS FROM StudentDB.STUDENTS;
SELECT COUNT(*) AS TOTAL_EMPLOYEES FROM EmployeeDB.EMPLOYEES;
SELECT COUNT(*) AS TOTAL_PRODUCTS FROM ShoppingDB.PRODUCTS;
SELECT SUM(SALARY) AS TOTAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT MAX(SALARY) AS MAXIMUM_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT MIN(SALARY) AS MINIMUM_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SUM(STOCK) AS TOTAL_STOCK FROM ShoppingDB.PRODUCTS;
SELECT AVG(PRICE) AS AVERAGE_PRICE FROM ShoppingDB.PRODUCTS;
SELECT MAX(PRICE) AS HIGHEST_PRICE FROM ShoppingDB.PRODUCTS;
SELECT MIN(PRICE) AS LOWEST_PRICE FROM ShoppingDB.PRODUCTS;
SELECT SUM(FEES) AS TOTAL_COURSE_FEES FROM CollegeDB.COURSES;
SELECT AVG(FEES) AS AVERAGE_COURSE_FEES FROM CollegeDB.COURSES;
SELECT MAX(FEES) AS MAXIMUM_COURSE_FEE FROM CollegeDB.COURSES;
SELECT MIN(FEES) AS MINIMUM_COURSE_FEE FROM CollegeDB.COURSES;
SELECT SUM(BOOKS_QUANTITY) AS TOTAL_BOOKS FROM LibraryDB.BOOKS;
SELECT AVG(PRICE) AS AVERGAE_BOOK_PRICE FROM LibraryDB.BOOKS;
SELECT MAX(PRICE) AS MAXIMUM_BOOK_PRICE FROM LibraryDB.BOOKS;
SELECT MIN(PRICE) AS MINIMUM_BOOK_PRICE FROM LibraryDB.BOOKS;
SELECT COUNT(DISTINCT DEPARTMENT) AS TOTAL_DEPARTMENTS FROM StudentDB.STUDENTS;

-- ALIAS WITH CASE

SELECT *, CASE 
    WHEN SALARY > 100000 THEN 'HIGH PAYING EMPLOYEE'
    WHEN SALARY > 50000 THEN 'MEDIUM PAYING EMPLOYEE'
    ELSE 'UNDER PAID'
END AS SALARY_CATEGORY
FROM EmployeeDB.EMPLOYEES;

SELECT *, CASE 
    WHEN MARKS>90 THEN 'GOOD'
    WHEN MARKS > 75 THEN 'OKAY'
    ELSE 'NEEDS IMPROVEMENT'
END AS RESULT_STATUS
FROM STUDENTDB.STUDENTS;

SELECT *, CASE
    WHEN SOTCK>50 THEN 'AVAILABLE'
    WHEN STOCK > 0 THEN 'NEEDS TO BE ORDERED'
    ELSE 'NO STOCK'
END AS STOCK_STATUS
FROM ShoppingDB.PRODUCTS;

SELECT *, CASE
    WHEN AGE>18 THEN 'GOOD'
    ELSE 'DRINK COMPLAN'
END AS AGE_CATEGORY
FROM StudentDB.STUDENTS;

SELECT *, CASE
    WHEN EXPERIENCE > 10 THEN 'SENIOR EXPERIENCED'
    WHEN EXPERIENCE >5 THEN 'TL'
    ELSE 'NEEDS EXPERIENCE'
END AS EXPERIENCE_LEVEL
FROM EmployeeDB.EMPLOYEES;

SELECT *, CASE
    WHEN PRICE>10000 THEN 'COSTLY'
    WHEN PRICE>5000 THEN 'BUDGET'
    ELSE 'CHEAP'
END AS PRICE_CATEGORY
FROM ShoppingDB.PRODUCTS;

SELECT *, CASE
    WHEN FEES>100000 THEN 'AI'
    WHEN FEES>50000 THEN 'DATASCIENCE'
    ELSE 'ENGINEERING'
END AS FEE_CATEGORY
FROM CollegeDB.COURSES;


SELECT *, CASE
    WHEN RATING>4 THEN 'GOOD MOVIE'
    WHEN RATRING>3 THEN 'AVERAGE MOVIE'
    ELSE 'DONT GO'
END AS RATING_CATEGORY
FROM MovieDB.MOVIES;

SELECT *, CASE
    WHEN EMAIL IS NOT NULL THEN 'EMAIL IS AVAILABLE'
    ELSE 'EMAIL IS NOT AVAILABLE'
END AS EMAIL_STATUS
FROM StudentDB.STUDENTS;

SELECT *, CASE
    WHEN EXPERIENCE>3 THEN 'PROMOTION AVAILABLE'
    ELSE 'PROMOTION NOT AVAILABLE'
END AS PROMOTION_STATUS
FROM EmployeeDB.EMPLOYEES;

-- TABLE ALIASES

SELECT E.EMPLOYEE_NAME, E.SALARY AS EMPLOYEE_NAME FROM EmployeeDB.EMPLOYEES AS E;
SELECT S.STUDENT_NAME AS STUDENT_NAME, S.DEPARTMENT AS DEPARTMENT FROM StudentDB.STUDENTS AS S;
SELECT P.NAME AS PRODUCT_NAME , P.PRICE AS PRICE FROM ShoppingDB.PRODUCTS AS P;
SELECT B.NAME AS BOOK_NAME, B.PRICE AS PRICE FROM LibraryDB.BOOKS AS B;
SELECT C.COURSE_NAME AS COURSE_NAME, C.FEES AS FEES FROM CollegeDB.COURSES AS C;
SELECT CU.CUSTOMERNAME AS CUSTOMER_NAME, CU.CITY AS CITY FROM ECommerceDB.CUSTOMERS AS CU;
SELECT E.SALARY AS EMPLOYEE_SALARY FROM EmployeeDB.EMPLOYEES AS E WHERE E.SALARY>50000;
SELECT P.PRICE AS PRICE FROM ShoppingDB.PRODUCTS AS P WHERE P.PRICE>10000;
SELECT E1.EMPLOYEENAME, E1.SALARY, E2.EMPLOYEENAME, E2.SALARY FROM EmployeeDB.EMPLOYEES E1 JOIN EMPLOYEES E2 ON E1.SALARY > E2.SALARY;
SELECT E.EMPLOYEE_ID, E.EMPLOYEENAME, D.DEPARTMENTID, D.DEPARTMENTNAME FROM EmployeeDB.EMPLOYEES AS E WHERE EXISTS  (SELECT * FROM DEPARTMENTS AS D);

-- ADVANCED ALIAS PRACTICE

SELECT EMPLOYEENAME AS EMPLOYEE_NAME, SALARY AS EMPLOYEE_SALARY, SALARY*12 AS ANNUAL_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT PRODUCTNAME AS PRODUCT_NAME, PRICE AS PRICE, QUANTITY_STOCK AS STOCK, SUM(PRICE*QUANTITY_STOCK) AS TOTAL_STOCK_VALUE FROM ShoppingDB.PRODUCTS;

SELECT NAME AS STUDNET_NAME, MARKS AS MARKS, 
CASE 
    WHEN MARKS>90 THEN 'GOOD'
    WHEN MARKS > 75 THEN 'OKAY'
    ELSE 'NEEDS IMPROVEMENT'
END AS RESULT_STATUS
FROM StudentDB.STUDENTS;

SELECT COURSENAME AS COURSE_NAME, FEES AS FEES, FEES*0.9 AS DISCOUNTED_FEES FROM CollegeDB.COURSES;

SELECT EMP_NAME AS EMPLOYEENAME, SALARY AS SALARY, 
CASE 
    WHEN SALARY > 100000 THEN 'HIGH PAYING EMPLOYEE'
    WHEN SALARY > 50000 THEN 'MEDIUM PAYING EMPLOYEE'
    ELSE 'UNDER PAID'
END AS SALARY_CATEGORY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME PRODUCT_NAME, PRICE AS PRICE, PRICE*0.18 AS GST_AMOUNT, PRICE+(PRICE*0.18) AS FINAL_PRICE FROM ShoppingDB.PRODUCTS;

SELECT NAME AS CUSTOMER_NAME, YEAR(REGDATE) AS REGISTRATION_DATE FROM ECommerceDB.CUSTOMERS;
SELECT EMPNAME AS EMPLOYEE_NAME, DATE_FORMAT(JOIN_DATE, 'dd-mm-yyyy') AS JOINING_DATE FROM EmployeeDB.EMPLOYEES;
SELECT STUDNETNAME AS STUDNET_NAME, LEN(STUDENT_NAME) AS NAME_LENGTH FROM StudentDB.STUDENTS;
SELECT BOOKNAME AS BOOK_NAME, PRICE*0.9 AS DISCOUNTED_PRICE FROM LibraryDB.BOOKS;
SELECT AVG(SALARY) AS AVG_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT * FROM EmployeeDB.EMPLOYEES WHERE SALARY > (SELECT AVG(SALARY) AS AVERAGE_SALARY FROM EmployeeDB.EMPLOYEES);
SELECT MAX(SALARY) AS MAX_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT MIN(SALARY) AS MIN_SALARY FROM EmployeeDB.EMPLOYEES;
SELECT SUM(QUANTITY*STOCK_PRICE) AS TOTAL_INVENTORY_VALUE FROM ShoppingDB.PRODUCTS;
SELECT DEPARTMENT_NAME AS DEPARTMENT_NAME, COUNT(EMPLOYEE) AS EMPLOYEE_COUNT FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT_NAME;
SELECT DEPARTMENT_NAME AS DEPARTMENT_NAME, AVG(SALARY) AS AVERAGE_SALARY FROM EmployeeDB.EMPLOYEES GROUP BY DEPARTMENT_NAME;
SELECT CATEGORY AS PRODUCT_CATEGORY, SUM(PRICE) AS TOTAL_REVENUE FROM ShoppingDB.PRODUCTS GROUP BY PRODUCT_CATEGORY;
SELECT CATEGORY AS PRODUCT_CATEGORY, MAX(PRICE) AS MAXIMUM_PRICE FROM ShoppingDB.PRODUCTS GROUP BY PRODUCT_CATEGORY;
SELECT CATEGORY AS PRODUCT_CATEGORY, MIN(PRICE) AS MINIMUM_PRICE FROM ShoppingDB.PRODUCTS GROUP BY PRODUCT_CATEGORY;
