-- EXISTS

SELECT * FROM EmployeeDB.DEPARTMENTS D WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.DEPARTMENTS D WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID);
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.DEPARTMENTS D WHERE D.DEPARTMENT_ID = S.DEPARTMENT_ID);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.ENROLLMENTS EN WHERE EN.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.PAYMENTS P WHERE P.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM EmployeeDB.DEPARTMENTS D WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY > 50000);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.SALARY > 70000);
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.STUDENTS S2 WHERE S2.DEPARTMENT_ID = S.DEPARTMENT_ID AND S2.AGE > 21);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.PRICE > 50000);
SELECT * FROM LibraryDB.BOOKS B WHERE EXISTS (SELECT 1 FROM LibraryDB.BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE > 1000);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 10000);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM CollegeDB.COURSES C WHERE EXISTS (SELECT 1 FROM CollegeDB.ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 10);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND YEAR(O.ORDER_DATE) = 2026);

-- NOT EXISTS

SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTDB.STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM STUDENTDB.ENROLLMENTS EN WHERE EN.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM CollegeDB.COURSES C WHERE NOT EXISTS (SELECT 1 FROM CollegeDB.ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM EmployeeDB.DEPARTMENTS D WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.PAYMENTS P WHERE P.CUSTOMER_ID = C.CUSTOMER_ID);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID);
SELECT * FROM STUDENTDB.STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM STUDENTDB.ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID);
SELECT * FROM EmployeeDB.DEPARTMENTS D WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY > 70000);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.SALARY > 70000);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.PRICE > 50000);
SELECT * FROM LibraryDB.BOOKS B WHERE NOT EXISTS (SELECT 1 FROM LibraryDB.BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE > 1000);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 1000);
SELECT * FROM CollegeDB.COURSES C WHERE NOT EXISTS (SELECT 1 FROM CollegeDB.ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'ACTIVE');
SELECT * FROM STUDENTDB.STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM STUDENTDB.ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.STATUS = 'SUBMITTED');

-- EXISTS WITH CONDITIONS

SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'ACTIVE');
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 5000);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 5);
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.COURSE_NAME = 'DATA ENGINEERING');
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.SALARY > 60000);
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.STUDENTS S2 WHERE S2.DEPARTMENT_ID = S.DEPARTMENT_ID AND S2.MARKS > 90);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.STOCK > 100);
SELECT * FROM LibraryDB.BOOKS B WHERE EXISTS (SELECT 1 FROM LibraryDB.BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE < 500);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'DELIVERED');
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'COMPLETED');
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.MARKS > 80);
SELECT * FROM CollegeDB.COURSES C WHERE EXISTS (SELECT 1 FROM CollegeDB.ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND MONTH(O.ORDER_DATE) = 8 AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.CITY = 'CHENNAI');
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP JOIN PROJECTS P ON EP.PROJECT_ID = P.PROJECT_ID WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND P.TEAM_NAME = 'DATA ENGINEERING');
SELECT * FROM STUDENTDB.STUDENTS S WHERE EXISTS (SELECT 1 FROM STUDENTDB.ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.FEES > 30000);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE EXISTS (SELECT 1 FROM ShoppingDB.PRODUCTS P2 WHERE P2.BRAND = P.BRAND AND P2.STOCK < 10);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.DESIGNATION = 'MANAGER');
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.QUANTITY > 10);
SELECT * FROM LibraryDB.BOOKS B WHERE EXISTS (SELECT 1 FROM LibraryDB.BOOKS B2 WHERE B2.AUTHOR = B.AUTHOR AND B2.BOOK_ID <> B.BOOK_ID);

-- NOT EXISTS WITH CONDITIONS 

SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.ORDER_AMOUNT > 10000);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 10);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'ACTIVE');
SELECT * FROM STUDENTDB.STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM STUDENTDB.ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.MARKS < 40);
SELECT * FROM CollegeDB.COURSES C WHERE NOT EXISTS (SELECT 1 FROM CollegeDB.ENROLLMENTS E WHERE E.COURSE_ID = C.COURSE_ID);
SELECT * FROM EmployeeDB.DEPARTMENTS D WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY > 60000);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.STOCK < 5);
SELECT * FROM LibraryDB.BOOKS B WHERE NOT EXISTS (SELECT 1 FROM LibraryDB.BOOKS B2 WHERE B2.CATEGORY = B.CATEGORY AND B2.PRICE > 2000);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'CANCELLED');
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'PENDING');
SELECT * FROM STUDENTDB.STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM STUDENTDB.ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.FEES > 50000);
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND MONTH(O.ORDER_DATE) = 8 AND YEAR(O.ORDER_DATE) = 2026);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP JOIN PROJECTS P ON EP.PROJECT_ID = P.PROJECT_ID WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND P.TEAM_NAME = 'ANALYTICS');
SELECT * FROM STUDENTDB.STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM STUDENTDB.ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID AND A.MARKS > 90);
SELECT * FROM CollegeDB.COURSES C WHERE NOT EXISTS (SELECT 1 FROM CollegeDB.ENROLLMENTS E JOIN STUDENTS S ON E.STUDENT_ID = S.STUDENT_ID WHERE E.COURSE_ID = C.COURSE_ID AND S.DEPARTMENT = 'IT');
SELECT * FROM ShoppingDB.PRODUCTS P WHERE NOT EXISTS (SELECT 1 FROM ShoppingDB.PRODUCTS P2 WHERE P2.CATEGORY = P.CATEGORY AND P2.PRICE > 100000);
SELECT * FROM EmployeeDB.EMPLOYEES E WHERE NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E2 WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID AND E2.DESIGNATION = 'MANAGER');
SELECT * FROM ECommerceDB.CUSTOMERS C WHERE NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'DELIVERED');
SELECT * FROM STUDENTDB.STUDENTS S WHERE NOT EXISTS (SELECT 1 FROM STUDENTDB.ENROLLMENTS E JOIN COURSES C ON E.COURSE_ID = C.COURSE_ID WHERE E.STUDENT_ID = S.STUDENT_ID AND C.COURSE_NAME = 'PYTHON');

-- CHALLENGE QUESTIONS

SELECT * 
FROM ECommerceDB.CUSTOMERS C
WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID)
AND NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'CANCELLED');

SELECT *
FROM ShoppingDB.PRODUCTS P
WHERE EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID)
AND NOT EXISTS (SELECT 1 FROM `RETURNS` R WHERE R.PRODUCT_ID = P.PRODUCT_ID);

SELECT *
FROM EmployeeDB.EMPLOYEES E
WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID)
AND NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEEPROJECTS EP WHERE EP.EMPLOYEE_ID = E.EMPLOYEE_ID AND EP.STATUS = 'COMPLETED');

SELECT *
FROM STUDENTDB.STUDENTS S
WHERE EXISTS (SELECT 1 FROM STUDENTDB.ENROLLMENTS E WHERE E.STUDENT_ID = S.STUDENT_ID)
AND NOT EXISTS (SELECT 1 FROM STUDENTDB.ASSIGNMENTS A WHERE A.STUDENT_ID = S.STUDENT_ID);

SELECT *
FROM EmployeeDB.DEPARTMENTS D
WHERE EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID)
AND NOT EXISTS (SELECT 1 FROM EmployeeDB.EMPLOYEES E WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID AND E.SALARY < 25000);

SELECT *
FROM ShoppingDB.PRODUCTS P
WHERE EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID)
AND NOT EXISTS (SELECT 1 FROM ShoppingDB.ORDERS O WHERE O.PRODUCT_ID = P.PRODUCT_ID AND O.QUANTITY > 20);

SELECT *
FROM ECommerceDB.CUSTOMERS C
WHERE EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'DELIVERED')
AND NOT EXISTS (SELECT 1 FROM ECommerceDB.ORDERS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID AND O.STATUS = 'CANCELLED');

SELECT *
FROM EmployeeDB.EMPLOYEES E
WHERE EXISTS (
    SELECT 1
    FROM EmployeeDB.EMPLOYEES E2
    WHERE E2.DEPARTMENT_ID = E.DEPARTMENT_ID
    AND E2.DESIGNATION = 'MANAGER'
)
AND E.DESIGNATION <> 'MANAGER';

SELECT *
FROM StudentDB.STUDENTS S
WHERE EXISTS (
    SELECT 1
    FROM StudentDB.STUDENTS S2
    WHERE S2.DEPARTMENT_ID = S.DEPARTMENT_ID
    AND S2.MARKS > 90
)
AND S.MARKS < 90;

SELECT *
FROM ShoppingDB.PRODUCTS P
WHERE EXISTS (
    SELECT 1
    FROM ShoppingDB.PRODUCTS P2
    WHERE P2.CATEGORY = P.CATEGORY
    AND P2.PRODUCT_TYPE = 'PREMIUM'
)
AND P.PRICE < 50000;