-- BETWEEN

SELECT * FROM StudentDB.students WHERE AGE BETWEEN 18 AND 25; 
SELECT * FROM EmployeeDB.Employees WHERE SALARY BETWEEN 30000 AND 60000;
SELECT * FROM HospitalDB.Patients WHERE AGE BETWEEN 20 AND 40;
SELECT * FROM LibraryDB.Books WHERE PRICE BETWEEN 500 AND 1000; 
SELECT * FROM ShoppingDB.Products WHERE PRICE BETWEEN 5000 AND 50000;
SELECT * FROM CollegeDB.Courses WHERE FEES BETWEEN 20000 AND 50000;
SELECT * FROM MovieDB.Movies WHERE RATING BETWEEN 3.0 AND 5.0;
SELECT * FROM HotelDB.Rooms WHERE PRICEPERDAY BETWEEN 2000 AND 5000;
SELECT * FROM StudentDB.students WHERE STUDENTID BETWEEN 101 AND 110;
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEEID BETWEEN 201 AND 210;

-- NOT BETWEEN

SELECT * FROM StudentDB.students WHERE AGE NOT BETWEEN 18 AND 25; 
SELECT * FROM EmployeeDB.Employees WHERE SALARY NOT BETWEEN 30000 AND 60000;
SELECT * FROM HospitalDB.Patients WHERE AGE NOT BETWEEN 20 AND 40;
SELECT * FROM LibraryDB.Books WHERE PRICE NOT BETWEEN 500 AND 1000; 
SELECT * FROM ShoppingDB.Products WHERE PRICE NOT BETWEEN 5000 AND 50000;
SELECT * FROM CollegeDB.Courses WHERE FEES NOT BETWEEN 20000 AND 50000;
SELECT * FROM MovieDB.Movies WHERE RATING NOT BETWEEN 3.0 AND 5.0;
SELECT * FROM HotelDB.Rooms WHERE PRICEPERDAY NOT BETWEEN 2000 AND 5000;
SELECT * FROM StudentDB.students WHERE STUDENTID NOT BETWEEN 101 AND 110;
SELECT * FROM EmployeeDB.Employees WHERE EMPLOYEEID NOT BETWEEN 201 AND 210;

-- BETWEEN WITH CONDITION

SELECT * FROM StudentDB.students WHERE AGE BETWEEN 18 AND 25 AND DEPARTMENT = 'CSE'; 
SELECT * FROM EmployeeDB.Employees WHERE SALARY BETWEEN 40000 AND 70000 AND DEPARTMENT = 'IT';
SELECT * FROM HospitalDB.Patients WHERE AGE BETWEEN 25 AND 50 AND GENDER = 'F';
SELECT * FROM LibraryDB.Books WHERE PRICE BETWEEN 500 AND 1500 AND CATEGORY = 'Technology';
SELECT * FROM ShoppingDB.Products WHERE PRICE BETWEEN 10000 AND 50000 AND CATEGORY = 'Electronics';
SELECT * FROM CollegeDB.Courses WHERE FEES BETWEEN 25000 AND 75000 AND DEPARTMENT = 'CSE';
SELECT * FROM HotelDB.Rooms WHERE PRICEPERDAY BETWEEN 2000 AND 4000 AND Availability = 'Y';
SELECT * FROM MovieDB.Movies WHERE RATING BETWEEN 3.0 AND 5.0 AND LANGUAGE = 'TAMIL';

-- NOT BETWEEN WITH CONDITION

SELECT * FROM StudentDB.students WHERE AGE NOT BETWEEN 18 AND 25 AND DEPARTMENT = 'IT'; 
SELECT * FROM EmployeeDB.Employees WHERE SALARY NOT BETWEEN 30000 AND 60000 AND DEPARTMENT = 'HR';
SELECT * FROM HospitalDB.Patients WHERE AGE NOT BETWEEN 20 AND 40 AND BLOODGROUP = 'O+VE';
SELECT * FROM LibraryDB.Books WHERE PRICE NOT BETWEEN 500 AND 1000 and category = 'Technology'; 
SELECT * FROM ShoppingDB.Products WHERE PRICE NOT BETWEEN 5000 AND 50000 AND CATEGORY = 'Electronics';
SELECT * FROM CollegeDB.Courses WHERE FEES NOT BETWEEN 20000 AND 50000 and department = 'IT';
SELECT * FROM HotelDB.Rooms WHERE PRICEPERDAY BETWEEN 2000 AND 4000 AND Availability = 'Y';

-- DATE WITH BETWEEN

SELECT * FROM EmployeeDB.Employees WHERE JOINING_DATE BETWEEN '2026-01-01' AND '2026-06-30';
SELECT * FROM HospitalDB.Patients WHERE ADMISSIONDATE BETWEEN '2026-08-01' AND '2026-08-20';
SELECT * FROM ShoppingDB.Products WHERE MANUFACTURINGDATE BETWEEN '2026-01-01' AND '2026-03-31';
SELECT * FROM ECOMMERCEDB.CUSTOMERS WHERE REGISTEREDDATE BETWEEN '2026-01-01' AND '2026-06-30';
SELECT * FROM MovieDB.Movies WHERE RELEASEDATE BETWEEN '2026-01-01' AND '2026-06-30';