-- BASIC CASE 

SELECT STUDNET_NAME, AGE,
CASE WHEN AGE>18 THEN 'ADULT'
ELSE 'MINOR'
END AS AGE_CATEGORY
FROM StudentDB.STUDNETS;

SELECT NAME, SALARY,
CASE WHEN SALARY>=60000 THEN 'HIGH'
WHEN SALARY>=40000 THEN 'MEDIUM'
ELSE 'LOW'
END AS SALARY_CATEGORY
FROM EmployeeDB.EMPLOYEE;

SELECT NAME, MARKS, 
CASE WHEN MARKS>=90 THEN 'EXCELLENT'
WHEN MARKS >=75 THEN 'VERG GOOD'
WHEN MARKS >=50 THEN 'GOOD'
ELSE 'FAIL'
END AS GRADE
FROM StudentDB.STUDNETS;

SELECT NAME, SALARY,
CASE WHEN SALARY >=50000 THEN 'ELIGIBLE'
ELSE 'MOT ELIGIBLE'
END AS ELIGIBILITY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, PRICE, 
CASE WHEN PRICE>=50000 THEN 'EXPENSIVE'
WHEN PRICE>=10000 THEN 'MODERATE'
ELSE 'AFFORDABLE'
END AS CATEGORY
FROM ShoppingDB.PRODUCTS;


SELECT NAME, PRICE,
CASE WHEN PRICE>=1000 THEN 'PREMIUM'
ELSE 'REGULAR'
END AS PRODUCT_TYPE
FROM ShoppingDB.PRODUCTS;

SELECT NAME, AGE,
CASE WHEN AGE>=60 THEN 'SENIOR CITIZEN'
WHEN AGE>=18 THEN 'ADULT'
ELSE 'MINOR'
END AS AGE_GROUP
FROM HospitalDB.PATIENTS;

SELECT NAME, EXPERIENCE,
CASE WHEN EXPERIENCE>=10 THEN 'SENIOR'
WHEN EXPERIENCE>=5 THEN 'INTERMEDIATE'
ELSE 'JUNIOR'
END AS CATEGORY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, FEES, 
CASE WHEN FEES>=50000 THEN 'HIGH FEE'
WHEN FEES>=30000 THEN 'MEDIUM FEE'
ELSE 'LOW FEE'
END AS FEE_STRUCTURE
FROM CollegeDB.COURSES;

SELECT NAME, STOCK,
CASE WHEN STOCK = 0 THEN 'OUT OF STOCK'
WHEN STOCK<10 THEN 'LOW STOCK'
ELSE 'AVAILABLE'
END AS STOCK_AVAILABLILITY
FROM ShoppingDB.PRODUCTS;

SELECT NAME, MARKS,
CASE WHEN MARKS>=40 THEN 'PASS'
ELSE 'FAIL'
END AS STATUS
FROM StudentDB.STUDNETS;

SELECT NAME, SALARY,
CASE WHEN SALARY>=70000 THEN 'HIGH SALARY'
ELSE 'NORMAL SALARY'
END AS SAL_CATEGORY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, PRICE,
CASE WHEN PRICE>1500 THEN 'COSTLY'
ELSE 'AFFORDABLE'
END AS CATEGORY FROM LibraryDB.BOOKS;

SELECT PRODUCT_NAME, QUANTITY, 
CASE WHEN QUANTITY>=100 THEN 'BULK STOCK'
ELSE 'NORMAL STOCK'
END AS AVAILABILITY FROM ShoppingDB.PRODUCTS;


SELECT NAME, RATING, 
CASE WHEN RATING>=4.5 THEN 'EXCELLENT'
WHEN RATING>=3 THEN 'GOOD'
ELSE 'AVERAGE'
END AS CATEGORY FROM MovieDB.MOVIES;

SELECT CUSTOMERNAME, AGE,
CASE WHEN AGE>=60 THEN 'SENIOR'
WHEN AGE>=30 THEN 'ADULT'
ELSE 'YOUNG'
END AS CATEGORY FROM ECommerceDB.CUSTOMERS;

SELECT NAME, SALARY,
CASE WHEN SALARY>=100000 THEN 'GRADE A'
WHEN  SALARY>=60000 THEN 'GRADE B'
ELSE 'GRADE C'
END AS GRADE FROM EmployeeDB.EMPLOYEES;

SELECT NAME, ATTENDANCE,
CASE WHEN ATTENDANCE>=90 THEN 'EXCELLENT'
WHEN ATTENDANCE >= 75 THEN 'GOOD'
ELSE 'LOW'
END AS ATTENDANCE_AVAILABLE FROM STUDENTDB.STUDENTS;

SELECT NAME, PRICE,
CASE WHEN PRICE>=100000 THEN 'LUXURY'
WHEN PRICE>=50000 THEN 'PREMIUM'
ELSE 'STANDARD'
END AS CATEGORY FROM ShoppingDB.PRODUCTS;


SELECT NAME, DURATION,
CASE WHEN DURATION>=12 THEN 'LONG TERM'
WHEN DURATION >=6 THEN 'MEDIUM TERM'
ELSE 'SHORT TERM'
END AS DURATION FROM CollegeDB.COURSES;

-- CASE WITH MULTIPLE CONDITIONS 

SELECT NAME, SALARY, DEPARTMENT,
CASE
    WHEN DEPARTMENT = 'IT' AND SALARY >= 60000 THEN 'IT HIGH SALARY'
    WHEN DEPARTMENT = 'HR' AND SALARY >= 50000 THEN 'HR HIGH SALARY'
    ELSE 'OTHER'
END AS SALARY_GROUP
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, DEPARTMENT, MARKS,
CASE
    WHEN DEPARTMENT = 'CSE' AND MARKS >= 80 THEN 'CSE EXCELLENT'
    WHEN DEPARTMENT = 'IT' AND MARKS >= 80 THEN 'IT EXCELLENT'
    ELSE 'OTHER'
END AS PERFORMANCE_CATEGORY
FROM STUDENTDB.STUDENTS;

SELECT NAME, CATEGORY, PRICE,
CASE
    WHEN CATEGORY = 'ELECTRONICS' AND PRICE >= 50000 THEN 'PREMIUM ELECTRONICS'
    WHEN CATEGORY = 'ELECTRONICS' AND PRICE < 50000 THEN 'REGULAR ELECTRONICS'
    ELSE 'OTHER CATEGORY'
END AS PRODUCT_CATEGORY
FROM STUDENTDB.PRODUCTS;

SELECT NAME, SALARY, EXPERIENCE,
CASE
    WHEN SALARY >= 70000 AND EXPERIENCE >= 5 THEN 'SENIOR HIGH SALARY'
    WHEN SALARY >= 50000 THEN 'GOOD SALARY'
    ELSE 'REGULAR'
END AS EMPLOYEE_CATEGORY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, AGE, ATTENDANCE,
CASE
    WHEN AGE >= 18 AND ATTENDANCE >= 75 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS ELIGIBILITY_STATUS
FROM STUDENTDB.STUDENTS;

SELECT NAME, STOCK,
CASE
    WHEN STOCK = 0 THEN 'OUT OF STOCK'
    WHEN STOCK < 10 THEN 'LOW STOCK'
    ELSE 'AVAILABLE'
END AS STOCK_STATUS
FROM ShoppingDB.PRODUCTS;

SELECT NAME, CATEGORY, PRICE,
CASE
    WHEN CATEGORY = 'TECHNOLOGY' AND PRICE > 1000 THEN 'PREMIUM TECHNOLOGY'
    WHEN CATEGORY = 'TECHNOLOGY' AND PRICE <= 1000 THEN 'REGULAR TECHNOLOGY'
    ELSE 'OTHER'
END AS BOOK_CATEGORY
FROM LibraryDB.BOOKS;

SELECT NAME, AGE, DISEASE,
CASE
    WHEN AGE >= 60 AND DISEASE IS NOT NULL THEN 'SENIOR PATIENT'
    WHEN AGE >= 18 THEN 'ADULT PATIENT'
    ELSE 'YOUNG PATIENT'
END AS PATIENT_CATEGORY
FROM HospitalDB.PATIENTS;

SELECT NAME, CITY, COUNTRY,
CASE
    WHEN CITY = 'CHENNAI' AND COUNTRY = 'INDIA' THEN 'CHENNAI CUSTOMER'
    ELSE 'OTHER CUSTOMER'
END AS CUSTOMER_CATEGORY
FROM ECommerceDB.CUSTOMERS;

SELECT NAME, DEPARTMENT, SALARY,
CASE
    WHEN DEPARTMENT = 'IT' AND SALARY >= 50000 THEN 'IT HIGH'
    WHEN DEPARTMENT = 'IT' AND SALARY < 50000 THEN 'IT NORMAL'
    ELSE 'OTHER DEPARTMENT'
END AS EMPLOYEE_CATEGORY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, PRICE, STOCK,
CASE
    WHEN PRICE >= 50000 AND STOCK > 10 THEN 'PREMIUM AVAILABLE'
    WHEN PRICE >= 50000 AND STOCK = 0 THEN 'PREMIUM UNAVAILABLE'
    ELSE 'REGULAR'
END AS PRODUCT_STATUS
FROM ShoppingDB.PRODUCTS;

SELECT NAME, MARKS, ATTENDANCE,
CASE
    WHEN MARKS >= 90 AND ATTENDANCE >= 90 THEN 'OUTSTANDING'
    WHEN MARKS >= 75 AND ATTENDANCE >= 75 THEN 'GOOD'
    ELSE 'NEEDS IMPROVEMENT'
END AS PERFORMANCE_STATUS
FROM StudentDB.STUDENTS;

SELECT NAME, EXPERIENCE, SALARY,
CASE
    WHEN EXPERIENCE >= 10 AND SALARY >= 80000 THEN 'SENIOR'
    WHEN EXPERIENCE >= 5 THEN 'MID-LEVEL'
    ELSE 'JUNIOR'
END AS EXPERIENCE_LEVEL
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, FEES, DURATION,
CASE
    WHEN FEES > 50000 AND DURATION >= 12 THEN 'PREMIUM LONG TERM'
    WHEN FEES > 30000 THEN 'STANDARD'
    ELSE 'BASIC'
END AS COURSE_CATEGORY
FROM CollegeDB.COURSES;

SELECT NAME, RATING, LANGUAGE,
CASE
    WHEN RATING >= 4.5 AND LANGUAGE = 'TAMIL' THEN 'TAMIL HIT'
    WHEN RATING >= 4.5 THEN 'HIT'
    ELSE 'AVERAGE'
END AS MOVIE_CATEGORY
FROM MovieDB.MOVIES;

SELECT NAME, CATEGORY, PRICE,
CASE
    WHEN CATEGORY = 'TECHNOLOGY' AND PRICE > 1000 THEN 'PREMIUM TECHNOLOGY'
    WHEN CATEGORY = 'SCIENCE' AND PRICE > 1000 THEN 'PREMIUM SCIENCE'
    ELSE 'REGULAR'
END AS BOOK_CATEGORY
FROM LibraryDB.BOOKS;

SELECT NAME, DEPARTMENT, SALARY,
CASE
    WHEN DEPARTMENT = 'IT' AND SALARY > 60000 THEN 'IT SENIOR'
    WHEN DEPARTMENT = 'HR' AND SALARY > 50000 THEN 'HR SENIOR'
    ELSE 'OTHER'
END AS EMPLOYEE_CATEGORY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, DEPARTMENT, AGE,
CASE
    WHEN DEPARTMENT = 'CSE' AND AGE < 21 THEN 'YOUNG CSE'
    WHEN DEPARTMENT = 'IT' AND AGE < 21 THEN 'YOUNG IT'
    ELSE 'OTHER'
END AS STUDENT_CATEGORY
FROM STUDENTDB.STUDENTS;

SELECT NAME, CITY, EMAIL,
CASE
    WHEN CITY = 'CHENNAI' AND EMAIL IS NOT NULL THEN 'VERIFIED CHENNAI'
    WHEN CITY = 'CHENNAI' AND EMAIL IS NULL THEN 'UNVERIFIED CHENNAI'
    ELSE 'OTHER CITY'
END AS CUSTOMER_STATUS
FROM ECommerceDB.CUSTOMERS;

SELECT NAME, BRAND, STOCK,
CASE
    WHEN BRAND IS NULL THEN 'UNKNOWN BRAND'
    WHEN STOCK = 0 THEN 'OUT OF STOCK'
    WHEN STOCK < 10 THEN 'LOW STOCK'
    ELSE 'AVAILABLE'
END AS PRODUCT_STATUS
FROM ShoppingDB.PRODUCTS;

-- CASE WITH NULL

SELECT EMAIL,
CASE
    WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
    ELSE 'EMAIL MISSING'
END AS EMAIL_STATUS
FROM StudentDB.STUDENTS;

SELECT DEPARTMENT,
CASE
    WHEN DEPARTMENT IS NOT NULL THEN 'DEPARTMENT ASSIGNED'
    ELSE 'DEPARTMENT MISSING'
END AS DEPARTMENT_STATUS
FROM EmployeeDB.EMPLOYEES;

SELECT BRAND,
CASE
    WHEN BRAND IS NOT NULL THEN 'BRAND AVAILABLE'
    ELSE 'BRAND MISSING'
END AS BRAND_STATUS
FROM ShoppingDB.PRODUCTS;

SELECT AUTHOR,
CASE
    WHEN AUTHOR IS NOT NULL THEN 'AUTHOR AVAILABLE'
    ELSE 'AUTHOR MISSING'
END AS AUTHOR_STATUS
FROM LibraryDB.BOOKS;

SELECT EMAIL,
CASE
    WHEN EMAIL IS NOT NULL THEN 'EMAIL AVAILABLE'
    ELSE 'EMAIL MISSING'
END AS EMAIL_STATUS
FROM ECommerceDB.CUSTOMERS;

SELECT DISEASE,
CASE
    WHEN DISEASE IS NOT NULL THEN 'DISEASE AVAILABLE'
    ELSE 'DISEASE NOT AVAILABLE'
END AS DISEASE_STATUS
FROM HospitalDB.PATIENTS;

SELECT NAME,
CASE
    WHEN DISCOUNT IS NOT NULL THEN 'DISCOUNT AVAILABLE'
    ELSE 'NO DISCOUNT'
END AS DISCOUNT_STATUS
FROM ShoppingDB.PRODUCTS;

SELECT PHONE,
CASE
    WHEN PHONE IS NOT NULL THEN 'PHONE AVAILABLE'
    ELSE 'PHONE MISSING'
END AS PHONE_STATUS
FROM StudentDB.STUDENTS;

SELECT MANAGER_NAME,
CASE
    WHEN MANAGER_NAME IS NOT NULL THEN 'MANAGER ASSIGNED'
    ELSE 'NO MANAGER'
END AS MANAGER_STATUS
FROM EmployeeDB.EMPLOYEES;

SELECT PUBLICATION_YEAR,
CASE
    WHEN PUBLICATION_YEAR IS NOT NULL THEN 'PUBLICATION YEAR AVAILABLE'
    ELSE 'YEAR UNKNOWN'
END AS PUBLICATION_STATUS
FROM LibraryDB.BOOKS;

-- CASE WITH AGGREGATE FUNCTIONS 

SELECT SUM(
    CASE
        WHEN SALARY >= 50000 THEN 1
        ELSE 0
    END
) AS EMPLOYEE_COUNT
FROM EmployeeDB.EMPLOYEES;

SELECT SUM(
    CASE
        WHEN MARKS >= 40 THEN 1
        ELSE 0
    END
) AS STUDENT_COUNT
FROM StudentDB.STUDENTS;

SELECT SUM(
    CASE
        WHEN STOCK = 0 THEN 1
        ELSE 0
    END
) AS OUT_OF_STOCK_COUNT
FROM ShoppingDB.PRODUCTS;

SELECT SUM(
    CASE
        WHEN PRICE >= 50000 THEN 1
        ELSE 0
    END
) AS PRODUCT_COUNT
FROM ShoppingDB.PRODUCTS;

SELECT SUM(
    CASE
        WHEN SALARY >= 50000 THEN SALARY
        ELSE 0
    END
) AS TOTAL_SALARY
FROM EmployeeDB.EMPLOYEES;

SELECT SUM(
    CASE
        WHEN CATEGORY = 'ELECTRONICS' THEN PRICE
        ELSE 0
    END
) AS TOTAL_PRICE
FROM ShoppingDB.PRODUCTS;

SELECT SUM(
    CASE
        WHEN STOCK > 10 THEN STOCK
        ELSE 0
    END
) AS TOTAL_STOCK
FROM ShoppingDB.PRODUCTS;

SELECT SUM(
    CASE
        WHEN ATTENDANCE >= 75 THEN 1
        ELSE 0
    END
) AS STUDENT_COUNT
FROM StudentDB.STUDENTS;

SELECT SUM(
    CASE
        WHEN DEPARTMENT = 'IT' THEN 1
        ELSE 0
    END
) AS IT_EMPLOYEE_COUNT
FROM EmployeeDB.EMPLOYEES;

SELECT SUM(
    CASE
        WHEN (PRICE * QUANTITY) > 10000 THEN PRICE * QUANTITY
        ELSE 0
    END
) AS TOTAL_SALES
FROM ShoppingDB.PRODUCTS;

-- ADVANCED CASE PRACTICE 

SELECT NAME, SALARY,
CASE
    WHEN SALARY >= 60000 THEN 'HIGH'
    WHEN SALARY >= 40000 THEN 'MEDIUM'
    ELSE 'LOW'
END AS SALARY_GRADE
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, MARKS,
CASE
    WHEN MARKS >= 90 THEN 'EXCELLENT'
    WHEN MARKS >= 75 THEN 'VERY GOOD'
    WHEN MARKS >= 50 THEN 'GOOD'
    ELSE 'FAIL'
END AS PERFORMANCE_LEVEL
FROM EmployeeDB.STUDENTS;

SELECT NAME, PRICE,
CASE
    WHEN PRICE >= 50000 THEN 'EXPENSIVE'
    WHEN PRICE >= 10000 THEN 'MODERATE'
    ELSE 'AFFORDABLE'
END AS PRICE_CATEGORY
FROM ShoppingDB.PRODUCTS;

SELECT NAME, PRICE,
CASE
    WHEN PRICE >= 1000 THEN 'PREMIUM'
    ELSE 'REGULAR'
END AS PRICE_CATEGORY
FROM LibraryDB.BOOKS;

SELECT NAME, AGE,
CASE
    WHEN AGE >= 60 THEN 'SENIOR'
    WHEN AGE >= 30 THEN 'ADULT'
    ELSE 'YOUNG'
END AS AGE_CATEGORY
FROM ECommerceDB.CUSTOMERS;

SELECT NAME, SALARY,
CASE
    WHEN SALARY >= 80000 THEN SALARY * 1.20
    WHEN SALARY >= 50000 THEN SALARY * 1.10
    ELSE SALARY * 1.05
END AS ANNUAL_SALARY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, PRICE, QUANTITY,
CASE
    WHEN QUANTITY = 0 THEN 'OUT OF STOCK'
    WHEN QUANTITY < 10 THEN 'LOW STOCK'
    ELSE 'AVAILABLE'
END AS STOCK_STATUS
FROM ShoppingDB.PRODUCTS;

SELECT NAME, MARKS, ATTENDANCE,
CASE
    WHEN MARKS >= 50 AND ATTENDANCE >= 75 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS ELIGIBILITY
FROM StudentDB.STUDENTS;

SELECT NAME, FEES,
CASE
    WHEN FEES >= 50000 THEN 'HIGH FEE'
    WHEN FEES >= 30000 THEN 'MEDIUM FEE'
    ELSE 'LOW FEE'
END AS FEE_CATEGORY
FROM CollegeDB.COURSES;

SELECT NAME, RATING,
CASE
    WHEN RATING >= 4.5 THEN 'EXCELLENT'
    WHEN RATING >= 3 THEN 'GOOD'
    ELSE 'AVERAGE'
END AS RATING_CATEGORY
FROM MovieDB.MOVIES;

SELECT NAME, SALARY,
CASE
    WHEN SALARY >= 90000 THEN 'A'
    WHEN SALARY >= 70000 THEN 'B'
    WHEN SALARY >= 50000 THEN 'C'
    ELSE 'D'
END AS GRADE
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, MARKS,
CASE
    WHEN MARKS >= 90 THEN 'DISTINCTION'
    WHEN MARKS >= 75 THEN 'FIRST CLASS'
    WHEN MARKS >= 50 THEN 'SECOND CLASS'
    ELSE 'FAIL'
END AS RESULT
FROM StudentDB.STUDENTS;

SELECT NAME, PRICE,
CASE
    WHEN PRICE >= 100000 THEN 'LUXURY'
    WHEN PRICE BETWEEN 50000 AND 99999 THEN 'PREMIUM'
    WHEN PRICE BETWEEN 10000 AND 49999 THEN 'STANDARD'
    ELSE 'BUDGET'
END AS PRODUCT_CATEGORY
FROM ShoppingDB.PRODUCTS;

SELECT NAME, EXPERIENCE,
CASE
    WHEN EXPERIENCE >= 10 THEN 'EXPERT'
    WHEN EXPERIENCE BETWEEN 5 AND 9 THEN 'EXPERIENCED'
    WHEN EXPERIENCE BETWEEN 2 AND 4 THEN 'INTERMEDIATE'
    ELSE 'FRESHER'
END AS EXPERIENCE_LEVEL
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, ATTENDANCE,
CASE
    WHEN ATTENDANCE >= 90 THEN 'EXCELLENT'
    WHEN ATTENDANCE BETWEEN 75 AND 89 THEN 'GOOD'
    WHEN ATTENDANCE BETWEEN 60 AND 74 THEN 'AVERAGE'
    ELSE 'POOR'
END AS ATTENDANCE_STATUS
FROM STUDENTDB.STUDENTS;

SELECT NAME,
CASE
    WHEN SALARY >= 80000 THEN SALARY * 1.20
    WHEN SALARY >= 50000 THEN SALARY * 1.10
    ELSE SALARY * 1.05
END AS SALARY_WITH_BONUS
FROM EmployeeDB.EMPLOYEES;

SELECT NAME,
CASE
    WHEN PRICE >= 100000 THEN PRICE * 0.20
    WHEN PRICE >= 50000 THEN PRICE * 0.15
    WHEN PRICE >= 10000 THEN PRICE * 0.10
    ELSE PRICE * 0.05
END AS DISCOUNT_AMOUNT
FROM ShoppingDB.PRODUCTS;

SELECT NAME, MARKS, ATTENDANCE,
CASE
    WHEN MARKS >= 50 AND ATTENDANCE >= 75 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS ELIGIBILITY
FROM StudentDB.STUDENTS;

SELECT NAME,
CASE
    WHEN EXPERIENCE >= 5 AND SALARY >= 60000 THEN 'ELIGIBLE'
    ELSE 'NOT ELIGIBLE'
END AS PROMOTION_ELIGIBILITY
FROM EmployeeDB.EMPLOYEES;

SELECT NAME, STOCK,
CASE
    WHEN STOCK = 0 THEN 'ORDER IMMEDIATELY'
    WHEN STOCK < 10 THEN 'REORDER'
    ELSE 'NO REORDER'
END AS REORDER_STATUS
FROM ShoppingDB.PRODUCTS;