SELECT *,ROW_NUMBER()OVER (ORDER BY SALARY ASC) AS SEQENTIAL_NUMBER FROM EmployeeDB.Employees;
SELECT *,ROW_NUMBER()OVER (ORDER BY SALARY DESC) AS SEQENTIAL_NUMBER FROM EmployeeDB.Employees;
SELECT *,ROW_NUMBER()OVER (PARTITION BY DEPARTMENT) AS SEQENTIAL_NUMBER FROM EmployeeDB.Employees;
SELECT * FROM (SELECT *,ROW_NUMBER()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS SEQENTIAL_NUMBER FROM EmployeeDB.Employees) A WHERE SEQENTIAL_NUMBER <4;
SELECT *,ROW_NUMBER()OVER (PARTITION BY DEPARTMENT ORDER BY MARKS DESC) AS SEQENTIAL_NUMBER FROM StudentDB.students;

SELECT *,RANK()OVER (ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees;
SELECT *,RANK()OVER (ORDER BY MARKS DESC) AS RANKING FROM StudentDB.students;
SELECT *,RANK()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees;
SELECT * FROM (SELECT *,RANK()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees) A WHERE RANKING = 1;
SELECT * FROM (SELECT *,RANK()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees) A WHERE RANKING < 4;

SELECT *,DENSE_RANK()OVER (ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees;
SELECT *,DENSE_RANK()OVER (ORDER BY MARKS DESC) AS RANKING FROM StudentDB.students;
SELECT *,DENSE_RANK()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees;
SELECT * FROM (SELECT *,DENSE_RANK()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees) A WHERE RANKING = 2;
-- RANK() - SKIPS THE NEXT VALUE IF PREVIOUS VALUES HAS SAME OUTPUT; DENSE_RANK - DOES NOT SKIPS THE NEXT VALUE.

SELECT *,SUM(SALARY)OVER (ORDER BY EMPLOYEEID) AS RUNNING_TOTAL FROM EmployeeDB.Employees;
SELECT *,SUM(SALES)OVER (ORDER BY SALES_DATE) AS RUNNING_TOTAL FROM SHOPPINGDB.SALES;
SELECT *,SUM(SALES_AMOUNT) OVER (PARTITION BY customer_id) AS running_total FROM SHOPPINGDB.SALES;
SELECT *,SUM(SALES_AMOUNT) OVER (PARTITION BY customer_id ORDER BY order_date) AS running_total FROM SHOPPINGDB.SALES;
SELECT EMPLOYEENAME,SALARY,SUM(SALARY) OVER(ORDER BY SALARY) AS CUMULATIVE_SALARY FROM EmployeeDB.Employees;

SELECT *,AVG(SALARY)OVER (ORDER BY EMPLOYEEID) AS RUNNING_AVGERAGE FROM EmployeeDB.Employees;
SELECT *,AVG(SALES)OVER (ORDER BY SALES_DATE) AS RUNNING_AVERAGE FROM SHOPPINGDB.SALES;
SELECT *,AVG(SALARY)OVER (PARTITION BY DEPARTMENT) AS RUNNING_AVERAGE FROM EmployeeDB.Employees;

SELECT *,SUM(salary) OVER () AS total_salary FROM EmployeeDB.Employees;
SELECT *,AVG(salary) OVER () AS total_salary FROM EmployeeDB.Employees;
SELECT *,MAX(salary) OVER () AS total_salary FROM EmployeeDB.Employees;
SELECT *,SUM(salary) OVER (PARTITION BY DEPARTMENT) AS total_salary FROM EmployeeDB.Employees;

SELECT *,LEAD(salary) OVER (ORDER BY EMPLOYEEID) AS next_employee_salary FROM EmployeeDB.Employees;
SELECT *,LEAD(JOINING_DATE) OVER (ORDER BY EMPLOYEEID) AS next_employee_JOINING_DATE FROM EmployeeDB.Employees;
SELECT *,LEAD(SALES_AMOUNT) OVER (ORDER BY SALES_date) AS NEXT_SALES_AMOUNT FROM SHOPPINGDB.SALES;
SELECT *, SALARY - LEAD(SALARY) OVER(ORDER BY EMPLOYEEID) AS DIFFERENCE FROM EmployeeDB.Employees;

SELECT *,LAG(salary) OVER (ORDER BY EMPLOYEEID) AS PREVIOUS_employee_salary FROM EmployeeDB.Employees;
SELECT *,LAG(JOINING_DATE) OVER (ORDER BY EMPLOYEEID) AS PREVIOUS_employee_JOINING_DATE FROM EmployeeDB.Employees;
SELECT *,LAG(SALES_AMOUNT) OVER (ORDER BY SALES_date) AS PREVIOUS_SALES_AMOUNT FROM SHOPPINGDB.SALES;
SELECT *, SALARY - LAG(SALARY) OVER(ORDER BY EMPLOYEEID) AS DIFFERENCE FROM EmployeeDB.Employees;

SELECT * FROM (SELECT *,ROW_NUMBER()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees) A WHERE RANKING = 1;
SELECT * FROM (SELECT *,DENSE_RANK()OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees) A WHERE RANKING = 2;
SELECT *,AVG(SALARY)OVER (PARTITION BY DEPARTMENT) AS RUNNING_AVERAGE, SALARY - AVG(SALARY)OVER (PARTITION BY DEPARTMENT) AS DIFFERENCE_SALARY FROM EmployeeDB.Employees;
SELECT *,LAG(salary) OVER (ORDER BY EMPLOYEEID) AS PREVIOUS_employee_salary,LEAD(salary) OVER (ORDER BY EMPLOYEEID) AS next_employee_salary FROM EmployeeDB.Employees;
SELECT EMPLOYEENAME,DEPARTMENT,SALARY,ROW_NUMBER() OVER(ORDER BY SALARY) AS CUMULATIVE_SALARY,
RANK()OVER (ORDER BY SALARY DESC) AS RANKING ,DENSE_RANK()OVER (ORDER BY SALARY DESC) AS RANKING FROM EmployeeDB.Employees;