-- BASIC DISTINCT

SELECT DISTINCT DEPARTMENT FROM StudentDB.students;
SELECT DISTINCT GENDER FROM StudentDB.students;
SELECT DISTINCT DEPARTMENT FROM EmployeeDB.Employees;
SELECT DISTINCT DESIGNATION FROM EmployeeDB.Employees; 
SELECT DISTINCT BLOODGROUP FROM HospitalDB.Patients;
SELECT DISTINCT DISEASE FROM HospitalDB.Patients;
SELECT DISTINCT CATEGORY FROM LibraryDB.Books; 
SELECT DISTINCT AUTHOR FROM LibraryDB.Books;
SELECT DISTINCT CATEGORY FROM ShoppingDB.Products;
SELECT DISTINCT BRAND FROM ShoppingDB.Products;
SELECT DISTINCT DEPARTMENT FROM CollegeDB.Courses;
SELECT DISTINCT DURATION FROM CollegeDB.Courses;
SELECT DISTINCT LANGUAGE FROM MovieDB.Movies;
SELECT DISTINCT GENRE FROM MovieDB.Movies;
SELECT DISTINCT CITY FROM ECommerceDB.Customers;
SELECT DISTINCT STATE FROM ECommerceDB.Customers;
SELECT DISTINCT COUNTRY FROM ECommerceDB.Customers;
SELECT DISTINCT DEPARTMENT,DESIGNATION FROM EmployeeDB.Employees;
SELECT DISTINCT CATEGORY, BRAND FROM ShoppingDB.Products;
SELECT DISTINCT CITY,STATE FROM ECommerceDB.Customers;

-- DISTINCT WITH CONDITIONS

SELECT DISTINCT DEPARTMENT FROM StudentDB.students WHERE AGE > 20;
SELECT DISTINCT DESIGNATION FROM EmployeeDB.Employees WHERE SALARY > 40000;
SELECT DISTINCT DISEASE FROM HospitalDB.Patients WHERE AGE > 30;
SELECT DISTINCT CATEGORY FROM LibraryDB.Books WHERE PRICE > 500;
SELECT DISTINCT BRAND FROM ShoppingDB.Products WHERE PRICE > 10000;
SELECT DISTINCT GENRE FROM MovieDB.Movies WHERE RATING > 4;
SELECT DISTINCT CITY FROM ECommerceDB.Customers WHERE COUNTRY = 'INDIA';
SELECT DISTINCT DEPARTMENT FROM StudentDB.students WHERE DEPARTMENT IN ('IT','CSE');
SELECT DISTINCT DEPARTMENT FROM EmployeeDB.Employees WHERE SALARY BETWEEN 30000 AND 60000;
SELECT DISTINCT CATEGORY FROM ShoppingDB.Products WHERE Availablestock > 10;

-- DISTINCT WITH PTHER OPERATORS
SELECT DISTINCT DEPARTMENT FROM StudentDB.students WHERE DEPARTMENT IN ('IT','CSE','ECE');
SELECT DISTINCT DEPARTMENT FROM EmployeeDB.Employees WHERE DEPARTMENT NOT IN ('HR','FINANCE');
SELECT DISTINCT CATEGORY FROM ShoppingDB.Products WHERE PRICE BETWEEN 5000 AND 50000;
SELECT DISTINCT CATEGORY FROM LibraryDB.Books WHERE PRICE NOT BETWEEN 500 AND 1000;
SELECT DISTINCT CITY FROM ECommerceDB.Customers WHERE EMAIL IS NOT NULL;
SELECT DISTINCT CITY FROM ECommerceDB.Customers WHERE EMAIL IS NULL; 
SELECT DISTINCT DEPARTMENT FROM EmployeeDB.Employees WHERE SALARY > 50000;
SELECT DISTINCT DEPARTMENT FROM StudentDB.students WHERE AGE NOT BETWEEN 18 AND 25;
SELECT DISTINCT BRAND FROM ShoppingDB.Products WHERE BRAND IS NOT NULL;
SELECT DISTINCT BLOODGROUP FROM HospitalDB.Patients WHERE DISEASE IS NULL;